.github/workflows/build_and_test.yml, .github/workflows/release.yml
Test MacOS wheels on 10.15 as well.
Successful run of release workflow: https://github.com/CQCL/tket/runs/3608780972
=> Build and test on MacOS 11.

.github/workflows/build_and_test.yml, .github/workflows/build_macos_wheel, .github/workflows/linuxbuildwheel, .github/workflows/nightly.yml, .github/workflows/pytket_docs.yml, .github/workflows/release.yml
Looks like `urllib3` is no longer a dependency of `conan` so the issue has gone away.
=> Remove conan/urllib3 workaround.

bubble/src/Gate/Rotation.cpp, bubble/tests/test_CompilerPass.cpp
And add a test.
The handling of the first case was incorrect: I'm not sure what I was thinking there. I've added commentary.
Fixes #9 .
=> Fix special-case handling in `tk1_angles_from_unitary`.

bubble/src/tketCMake.cmake, recipes/tket-tests/conanfile.py, recipes/tket-tests/test_package/conanfile.py, recipes/tket/conanfile.py
@lmondada apologies. Somehow I had omitted to commit these changes, which are necessary to make it work, to the feature branch for #5 .
Tested here: https://github.com/CQCL/tket/actions/runs/1248010668
=> Add relevant options to tket and tket-tests recipes for coverage report.

pytket/pytket/qasm/qasm.py, pytket/tests/qasm_test.py
=> Handle parameters in conditional gates when converting to QASM.

bubble/tests/test_Routing.cpp
These lines test the same thing as the proceeding one.
=> Removed unnecessary test lines

.github/workflows/docs.yml
=> Update `gh-pages` branch from `develop` before building docs.

pytket/binders/circuit/main.cpp, pytket/docs/changelog.rst, pytket/tests/circuit_test.py
The logic is copied from https://github.com/CQCL/tket/blob/e2a2bb86d8728b5ed3dd4cc06d9bb2b0b8d62a38/tket/src/Predicates/Predicates.cpp#L433
=> Feature/expose is_clifford to pytket Op

pytket/tests/circuit_test.py, tket/src/Gate/Rotation.cpp
=> Fix numerical instability in construction of TK1 from unitary

.github/workflows/build_and_test.yml, pytket/docs/changelog.rst, pytket/pytket/utils/operators.py, pytket/tests/qubitpaulioperator_test.py, pytket/tests/requirements-openfermion.txt
A PR on the pytket example repo with fixed notebooks is following immediately!
=> [feature] Dropped OpenFermion support

recipes/symengine/conanfile.py
(This just changes the recipe and builds the packages, doesn't update the tket dependency.)
=> Build symengine 0.9.0.

tket/src/Placement/CMakeLists.txt, tket/src/Placement/NeighbourPlacements.cpp, tket/src/Placement/include/Placement/NeighbourPlacements.hpp, tket/src/Utils/include/Utils/UnitID.hpp, tket/tests/Placement/test_NeighbourPlacements.cpp, tket/tests/Placement/test_Placement.cpp, tket/tests/tkettestsfiles.cmake
Waiting to rebase on rv3 (https://github.com/CQCL/tket/pull/167) once that is merged into develop
=> [feature] [rv3] Generate random nearby placements

pytket/setup.py
try to fix develop test run on python
=> [bugfix] fix develop issue with sympy

pytket/binders/mapping.cpp
=> remove documentation of single qubit problem

pytket/mypy.ini, pytket/pytket/passes/_decompositions.py, pytket/pytket/qasm/qasm.py, pytket/pytket/utils/operators.py, pytket/pytket/utils/symbolic.py, pytket/setup.py, pytket/tests/circuit_test.py, pytket/tests/qubitpaulioperator_test.py, pytket/tests/transform_test.py, pytket/tests/utils_test.py
=> Bugfix/add sympy 1.10 support

pytket/docs/changelog.rst, pytket/pytket/backends/status.py, pytket/tests/backend_test.py
Extend CircuitStatus to support a few new fields, such as timestamps for
changes in status, queue position and detailed error information.
=> [feature] Enhance circuit statuses

tket/src/Mapping/MappingManager.cpp, tket/tests/test_LexiRoute.cpp
Ancilla qubits may be used during mapping, which may leave a circuit with more qubits than the architecture has nodes temporarily. This is typically resolved during routing, as unplaced logical qubits will be assigned to ancilla qubits. However, qubits with only single qubit gates are unlabelled during mapping and the previous mapping labelling would not assign these to ancilla qubits, leaving cases where there were no free architecture qubits to assign an unlabelled qubit to.
This fixes this and updates the labelling used.
=> Update post mapping labelling

pytket/binders/pauli.cpp
Strictly speaking this is an API change, but I think we can call it a bugfix.
=> Correct parameter name.

.github/workflows/coverage.yml, pytket/docs/changelog.rst, tket/src/Gate/Gate.cpp, tket/src/Gate/Rotation.cpp, tket/src/Gate/include/Gate/Gate.hpp, tket/tests/Circuit/test_Symbolic.cpp
=> Work around issues arising from symbolic squashing.

pytket/pytket/backends/backendresult.py
=> Don't permute rows/columns if permutation is the identity.

pytket/binders/predicates.cpp, pytket/docs/changelog.rst, pytket/tests/predicates_test.py
=> Add `NoBarriersPredicate` to pytket

pytket/docs/passes.rst
Added auto_rebase and auto_squash pass to API documentation.
=> autorebase

.github/workflows/lint.yml
=> Avoid pylint 2.13.6.

tket/tests/test_json.cpp
=> remove comment

.github/workflows/linuxbuildwheel
Tested [here](https://github.com/CQCL/tket/runs/6468932093).
Cf. failing build [here](https://github.com/CQCL/tket/runs/6468838914).
=> Fix manylinux builds.

tket/src/Transformations/Decomposition.cpp, tket/tests/test_GlobalisePhasedX.cpp, tket/tests/test_Synthesis.cpp
Preparing the notebook this morning, I stumbled upon an edge case that wasn't handled well by `choose_strategy`.
=> [bugfix] Decomposition strategy special case

pytket/package.md
Fixed typo and redundant project description heading.
=> fixed pypi typo and formatting

tket/tests/WeightSubgrMono/SolvingProblems/test_RandomGraphs.cpp, tket/tests/WeightSubgrMono/SolvingProblems/test_SnakeIntoSquareGrid.cpp, tket/tests/WeightSubgrMono/SolvingProblems/test_SquareGrids.cpp
Tested with complete coverage run [here](https://github.com/CQCL/tket/actions/runs/2560135162).
=> Increase some timeouts in WSM tests.

pytket/pytket/circuit/display/circuit.html
latest circuit renderer version.
=> bump circuit renderer to v0.2

tket/src/ArchAwareSynth/Path.cpp, tket/src/Architecture/Architecture.cpp
=> Use logical rather than bitwise operations in boolean expressions.

pytket/conanfile.txt, recipes/pybind11/conanfile.py, tket/src/Circuit/include/Circuit/Circuit.hpp, tket/src/Circuit/macro_circ_info.cpp
Also a small tweak to Circuit::begin() to permit forwarding to operator++. (Pytket build fails without this.)
=> Update to pybind11 2.10.0

tket/src/Utils/MatrixAnalysis.cpp, tket/tests/test_TwoQubitCanonical.cpp
Restore tests deleted in [this commit](https://github.com/CQCL/tket/pull/477/commits/5a62580cf9ba5c8fb375a8f63c9f2ba85ae75fd1).
=> Improve handling of Clifford circuits in KAK decomposition

tket/src/Circuit/CircPool.cpp, tket/src/Circuit/CircUtils.cpp, tket/src/Circuit/ControlledGates.cpp, tket/src/Circuit/basic_circ_manip.cpp, tket/src/Circuit/include/Circuit/CircUtils.hpp, tket/src/Circuit/include/Circuit/Circuit.hpp, tket/src/Circuit/macro_circ_info.cpp, tket/src/Circuit/setters_and_getters.cpp, tket/src/Gate/Gate.cpp, tket/src/Transformations/BasicOptimisation.cpp, tket/src/Transformations/PQPSquash.cpp, tket/tests/Circuit/test_Circ.cpp, tket/tests/Circuit/test_CircPool.cpp, tket/tests/Ops/test_Ops.cpp, tket/tests/test_PhaseGadget.cpp, tket/tests/test_Synthesis.cpp
With this PR `commute_through_multis` supports conditionals, commuting through TK1 and others when possible (in edge cases) and looks nicer.
=> [feature] Smarter `commute_through_multis`

.github/workflows/build_and_test.yml
There is more to do, but I'd like to proceed incrementally so that changes can be road-tested. This is a first step.
=> Combine ubuntu, macos and windows workflows.

pytket/conanfile.txt, pytket/docs/changelog.rst, recipes/tket-proptests/conanfile.py, recipes/tket-tests/conanfile.py, recipes/tket/conanfile.py, tket/src/Transformations/RzPhasedXSquash.cpp, tket/tests/test_Synthesis.cpp
=> Fix phase issue in SquashRzPhasedX

.github/workflows/build-symengine.yml, .github/workflows/build_and_test.yml, .github/workflows/build_libs.yml, .github/workflows/publish_tket_package.yml, .github/workflows/release.yml, .github/workflows/test_libs.yml, .github/workflows/test_libs_all.yml
Since conan does not yet support apple-clang 14.
=> Use xcode version 13.4.1 on macos-12

pytket/docs/index.rst
Add temporary workaround to resize quantinuum logo
=> add logo workaround

pytket/pytket/circuit/display/circuit.html
Adds the required config for the options to work properly.
=> update circuit display to v0.3

.github/workflows/build_and_test.yml, .github/workflows/build_libs.yml, .github/workflows/coverage.yml, .github/workflows/linuxbuildlib, .github/workflows/linuxbuildpackages, .github/workflows/linuxbuildwheel, .github/workflows/packages.yml, .github/workflows/publish_tket_package.yml, .github/workflows/release.yml, .github/workflows/test_libs.yml, .github/workflows/test_libs_all.yml, .github/workflows/valgrind.yml, README.md
Conan v2 will be arriving soon (in beta now). Until we're ready for it, let's make sure we always install v1 in the CI workflows.
=> Install conan v1

.github/dependabot.yml
This should generate a new PR when any update to an external github action is detected.
=> Add dependabot file to check periodically for actions updates

pytket/pytket/utils/operators.py, pytket/tests/qubitpaulioperator_test.py
=> Fix serialization and deserialization of symbolic `QubitPauliString` coefficients

CITATION.cff
Added a citation file with the tket white paper as the preferred refernce.
About CITATION.cff files -> https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
=> add citation file to tket repo

pytket/pytket/qasm/qasm.py, pytket/tests/qasm_test.py
=> Support `OpType.Phase` in QASM converters

pytket/binders/passes.cpp, pytket/binders/predicates.cpp, pytket/conanfile.txt, pytket/docs/changelog.rst, pytket/tests/predicates_test.py, pytket/tests/transform_test.py, recipes/tket-proptests/conanfile.py, recipes/tket-tests/conanfile.py, recipes/tket/conanfile.py, tket/src/Circuit/Circuit.cpp, tket/src/Circuit/include/Circuit/Circuit.hpp, tket/src/Circuit/macro_manipulation.cpp, tket/src/Predicates/Predicates.cpp, tket/src/Predicates/include/Predicates/Predicates.hpp, tket/src/Transformations/Rebase.cpp, tket/tests/test_Rebase.cpp, tket/tests/test_Synthesis.cpp
Fixes #576 .
After merging I plan to make a dev release and then update all the extensions to make sure they work with this change,
=> Correct handling of conditional phases

pytket/conanfile.txt, recipes/tket-proptests/conanfile.py, recipes/tket-tests/conanfile.py, recipes/tket/conanfile.py, tket/src/CMakeLists.txt, tket/tests/CMakeLists.txt
We can remove this once https://github.com/boostorg/boost/issues/688 is resolved.
=> suppress xcode 14 compiler error

.github/workflows/build_and_test.yml, .github/workflows/build_libs.yml, .github/workflows/publish_tket_package.yml, .github/workflows/release.yml, .github/workflows/test_libs.yml, .github/workflows/test_libs_all.yml, README.md, pytket/docs/changelog.rst, pytket/docs/getting_started.rst, pytket/docs/index.rst, pytket/docs/install.rst, pytket/tests/requirements.txt, pytket/tests/zx_diagram_test.py
Closes #646 .
Will modify names of required CI checks if approved.
Release workflow tested [here](https://github.com/CQCL/tket/actions/runs/3759526258).
=> Add support for Python 3.11 and remove support for 3.8

.github/workflows/release.yml
Forgot to update the Python version here.
=> Fix docs build for releases

pytket/conanfile.txt, recipes/tket-proptests/conanfile.py, recipes/tket-tests/conanfile.py, recipes/tket/conanfile.py, tket/proptests/CMakeLists.txt
=> Suppress warning when building proptests

recipes/tket-tests/conanfile.py
This was missed from the merge in https://github.com/CQCL/tket/pull/741/commits/40975ff8f84939af906666042ece77a6c0176f28 .
=> Fix catch2 version.

pytket/docs/changelog.rst, pytket/pytket/circuit/display/circuit.html
=> Update to pytket-circuit-renderer 0.5

pytket/binders/circuit/boxes.cpp, pytket/docs/changelog.rst, pytket/tests/circuit_test.py
=> Cast vector keys to tuples

pytket/conanfile.txt, pytket/docs/changelog.rst, pytket/pytket/circuit/__init__.py, recipes/tket-proptests/conanfile.py, recipes/tket-tests/conanfile.py, recipes/tket/conanfile.py, tket/src/Circuit/basic_circ_manip.cpp, tket/tests/Circuit/test_Circ.cpp
=> Throw error rather than abort when trying to add qubit or bit with existing name

.github/workflows/build_and_test.yml, CONTRIBUTING.md, pytket/conanfile.txt, pytket/docs/display.rst, pytket/docs/requirements.txt, recipes/tket-proptests/conanfile.py, recipes/tket-tests/conanfile.py, recipes/tket/conanfile.py, tket/src/ArchAwareSynth/Path.cpp, tket/src/Circuit/ControlledGates.cpp, tket/src/Circuit/include/Circuit/Command.hpp, tket/src/Mapping/LexiRoute.cpp, tket/src/Predicates/include/Predicates/CompilationUnit.hpp, tket/src/Transformations/BasicOptimisation.cpp, tket/tests/Circuit/test_Boxes.cpp, tket/tests/test_ControlDecomp.cpp, tket/tests/test_TwoQubitCanonical.cpp
Necessary because v15 isn't available from brew now: https://formulae.brew.sh/formula/clang-format .
=> Use clang-format v16

pytket/docs/changelog.rst, pytket/setup.py
Closes https://github.com/CQCL/pytket/issues/224 .
=> Update to networkx 3

pytket/pytket/utils/operators.py, pytket/tests/utils_test.py
Resolves #801 .  Hopefully the test actually passes - apologies if not, I was struggling to get an editable install locally.
=> Make QubitPauliOperator.__setitem__ update all_qubits property

.github/workflows/build_and_test.yml
make the build docs available in the PR checks
=> add docs upload

pytket/binders/predicates.cpp, pytket/conanfile.txt, pytket/docs/changelog.rst, pytket/pytket/backends/backendinfo.py, pytket/tests/predicates_test.py, schemas/predicate_v1.json, tket/conanfile.py, tket/include/Predicates/Predicates.hpp, tket/proptest/conanfile.py, tket/src/Predicates/Predicates.cpp, tket/test/conanfile.py, tket/test/src/test_Predicates.cpp, tket/test/src/test_json.cpp
add new max n classical register predicate
=> add max n classical register

.github/workflows/build_and_test.yml
Needed for upload after push to `develop`.
=> Test pytket with coverage on push as well as pull_request

.github/workflows/build_and_test.yml, .github/workflows/build_libs.yml, .github/workflows/packages.yml, .github/workflows/release.yml, .github/workflows/test_libs.yml, .github/workflows/test_libs_all.yml
No need to default to conan 1 on M1 anymore.
=> Don't revert to conan 1

pytket/docs/changelog.rst, pytket/pytket/utils/expectations.py, pytket/tests/utils_test.py
Fixes issue found by @daniel-mills-cqc .
=> Only run circuits with non-identity Paulis

pytket/docs/opensource.rst
=> Update broken link for Eigen

pytket/pytket/backends/backend.py, pytket/pytket/backends/resulthandle.py, pytket/tests/simulator/tket_sim_backend.py
Fixes breaking change from #987
=> fix previously renamed type-def (ResultIdTuple back to _ResultIdTuple)

pytket/conanfile.py, pytket/docs/changelog.rst, tket/conanfile.py, tket/include/tket/Circuit/ConjugationBox.hpp, tket/src/Circuit/ConjugationBox.cpp, tket/test/src/Circuit/test_Boxes.cpp
=> Implement `symbol_substitution()` and `free_symbols()` for `ConjugationBox`

pytket/docs/changelog.rst, pytket/pytket/qasm/qasm.py, pytket/tests/qasm_test.py
=> Fix pytket-to-QASM conversion when individual bits of registers used in range predicates are later set

pytket/tests/circuit_test.py, schemas/circuit_v1.json
=> Bound the number of box properties in json schema

pytket/conanfile.py, pytket/docs/changelog.rst, tket/conanfile.py, tket/src/Transformations/BasicOptimisation.cpp, tket/test/src/test_Synthesis.cpp
=> Handle symbolic angles in `ZZPhase_to_Rz`.

pytket/docs/changelog.rst, pytket/docs/passes.rst, pytket/pytket/passes/__init__.py, pytket/pytket/passes/passselector.py, pytket/pytket/passes/superpass.py, pytket/tests/compilation_test.py
Add a compilation pass for trying a list of passes on a circuit and apply the best.
=> add superpass

.github/workflows/build_and_test.yml, .github/workflows/build_libs.yml, .github/workflows/coverage.yml, .github/workflows/linuxbuildlib, .github/workflows/linuxbuildpackages, .github/workflows/linuxbuildwheel, .github/workflows/packages.yml, .github/workflows/release.yml, .github/workflows/test_libs.yml, .github/workflows/test_libs_all.yml, .github/workflows/valgrind.yml, conan-profiles/linux-armv8-gcc10-libstdc++, conan-profiles/linux-x86_64-gcc10-libstdc++, conan-profiles/macos-11, conan-profiles/macos-12, conan-profiles/macos-armv8-clang14, conan-profiles/ubuntu-22.04, conan-profiles/windows-2022, pytket/conanfile.py, tket/conanfile.py
=> Add conan profiles for CI to source control

pytket/conanfile.py, tket/conanfile.py
I've uploaded new revisions of tkwsm and tktokenswap; this should make CI builds work again.
=> Bump tket version.

pytket/pytket/wasm/wasm.py
Add an additional check if the function is within the file
=> add aditional check for index out of array functions

pytket/binders/include/typecast.hpp, pytket/docs/changelog.rst, pytket/tests/circuit_test.py
=> Bugfix/bind `sympy.exp()`

pytket/conanfile.py, pytket/docs/changelog.rst, pytket/pytket/utils/operators.py, pytket/tests/circuit_test.py, tket/conanfile.py, tket/src/Circuit/macro_circ_info.cpp
=> Ensure determinate order of `Phase` commands

.github/workflows/build_and_test.yml, README.md, pytket/conanfile.py, tket/CMakeLists.txt, tket/conanfile.py
`ccache 4.8.3` includes a bugfix that makes this possible 🥳
=> Ccache windows dynamic build

pytket/pytket/qasm/qasm.py, pytket/tests/qasm_test.py
=> Better handling for invalid QASM register names

libs/tktokenswap/CMakeLists.txt, libs/tktokenswap/conanfile.py, libs/tktokenswap/test/conanfile.py, libs/tktokenswap/test/src/TableLookup/PermutationTestUtils.cpp, libs/tktokenswap/test/src/TestUtils/DecodedProblemData.cpp, libs/tkwsm/conanfile.py, libs/tkwsm/test/conanfile.py
=> [tktokenswap, tkwsm] Update dependencies and add missing include

.github/workflows/build_and_test.yml
Temporary workaround for #1135 .
=> Pin to pybind11-stubgen 2.3.6.

pytket/binders/passes.cpp, pytket/docs/changelog.rst, pytket/pytket/_tket/passes.pyi, pytket/tests/predicates_test.py
=> Deprecate `SynthesiseHQS`

.github/workflows/build-without-conan.yml, build-without-conan.md, libs/tkassert/test/conanfile.py, libs/tklog/test/conanfile.py, libs/tkrng/test/conanfile.py, libs/tktokenswap/test/conanfile.py, libs/tkwsm/test/conanfile.py, pytket/conanfile.py, tket/conanfile.py
Use latest version of catch2 for building C++ tests.
=> Update to catch2 3.5.0

.gitignore
Add the .vs folder (for Visual Studio) to .gitignore file.
N/A
=> Add Visual Studio to .gitignore.

.github/workflows/build_and_test.yml, .github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/test_libs.yml
update of the actions, see https://github.com/CQCL/tket/pull/1183 and https://github.com/CQCL/tket/pull/1182
=> update github actions

.github/workflows/build-without-conan.yml, .github/workflows/build_and_test.yml, .github/workflows/build_libs.yml, .github/workflows/linuxbuildlib, .github/workflows/packages.yml, .github/workflows/release.yml, .github/workflows/test_libs.yml, .github/workflows/test_libs_all.yml, README.md, pytket/conanfile.py, pytket/docs/changelog.rst, pytket/docs/getting_started.rst, pytket/docs/index.rst, pytket/docs/install.rst, pytket/package.md, pytket/setup.py, tket/conanfile.py
Support Python 3.{10,11,12} instead of 3.{9,10,11}.
Closes #1172 .
=> Support python 3.12; drop python 3.9

pytket/conanfile.py, pytket/docs/changelog.rst, pytket/docs/conf.py, tket/conanfile.py
Merge changes from `main` branch and bump tket version.
=> Feature/main merge 1.23.0

.github/workflows/build-without-conan.yml, build-without-conan.md, libs/tkassert/test/conanfile.py, libs/tklog/test/conanfile.py, libs/tkrng/test/conanfile.py, libs/tktokenswap/test/conanfile.py, libs/tkwsm/test/conanfile.py, pytket/conanfile.py, tket/conanfile.py
Update to catch2 3.5.2 for all C++ tests. I've already uploaded this to the artifactory.
=> Update to catch2 3.5.2

pytket/pytket/zx/tensor_eval.py, pytket/tests/zx_diagram_test.py
Just show a warning.
Fixes #1227 .
=> Don't raise exception if zx is not installed

.github/workflows/build_libs.yml, .github/workflows/linuxbuildlib
Only authenticate to the private artifactory if we need to upload something.
Fixes #1237
=> Only authenticate if necessary.

pytket/docs/check_circuit_class_docs.py, pytket/docs/circuit.rst, pytket/docs/circuit_class.rst, pytket/docs/conf.py
Cherry-picked the commit for the changes to the API docs made in #1178  into the `docmain` branch
=> Cherry pick changes to circuit API docs to `docmain` branch

pytket/docs/circuit.rst
=> Add missing ToffoliBoxSynthStrat to docs

.github/workflows/build-without-conan.yml, build-without-conan.md, libs/tkassert/test/conanfile.py, libs/tklog/test/conanfile.py, libs/tkrng/test/conanfile.py, libs/tktokenswap/test/conanfile.py, libs/tkwsm/test/conanfile.py, pytket/conanfile.py, tket/conanfile.py
=> Update to catch2 3.5.3.

pytket/binders/passes.cpp, pytket/pytket/_tket/passes.pyi
Document that it also removes identity gates.
=> Improve documentation of SquashRzPhasedX.

pytket/docs/requirements.txt
Upgrading to the latest sphinx-book-theme version.
Ensures consistency with the example notebooks theme.
=> Upgrade docs theme to sphinx-book-theme 1.1.2

.github/workflows/build-with-nix.yml, .github/workflows/build_and_test.yml, .github/workflows/build_libs.yml, .github/workflows/packages.yml, .github/workflows/release.yml, .github/workflows/test_libs.yml, .github/workflows/test_libs_all.yml, conan-profiles/macos-13-xlarge, conan-profiles/macos-14, conan-profiles/macos-armv8-clang14, pytket/conanfile.py, tket/conanfile.py
Release workflow tested [here](https://github.com/CQCL/tket/actions/runs/8687805189).
=> Use `macos-14` runner to build MacOS arm64 wheels

pytket/package.md, pytket/pytket/__init__.py, pytket/setup.py
Updating the pypi page to remove a couple of legacy references to CQC
=> Update pypi project description

pytket/binders/include/UnitRegister.hpp, pytket/conanfile.py, tket/conanfile.py, tket/include/tket/Characterisation/Cycles.hpp, tket/include/tket/Circuit/ClassicalExpBox.hpp, tket/include/tket/Mapping/AASLabelling.hpp, tket/include/tket/Mapping/LexiLabelling.hpp, tket/include/tket/Mapping/RoutingMethod.hpp, tket/include/tket/Placement/Placement.hpp, tket/include/tket/Predicates/CompilerPass.hpp, tket/include/tket/Predicates/Predicates.hpp, tket/src/Mapping/BoxDecomposition.cpp, tket/src/Mapping/LexiRouteRoutingMethod.cpp, tket/src/Mapping/RoutingMethodCircuit.cpp, tket/src/Placement/Placement.cpp, tket/test/src/test_MappingManager.cpp
Run do-clang-format script with clang-format 18.1.4 installed.
https://github.com/CQCL/tket/issues/1366
=> Run do-clang-format with clang-format 18.1.4

pytket/package.md, pytket/setup.py
=> update tket email

conan-profiles/windows-2022, pytket/conanfile.py, tket/conanfile.py
Testing here: https://github.com/CQCL/tket/actions/runs/9417545477/job/25942951717
Fixes #1246 .
=> Update Windows compiler version.

pytket/docs/changelog.rst, pytket/pytket/passes/__init__.py, pytket/pytket/passes/resizeregpass.py, pytket/tests/compilation_test.py
Solves https://github.com/CQCL/tket/issues/1478
=> add pass: scratch_reg_resize_pass

pytket/docs/changelog.rst, pytket/pytket/circuit/display/static/head_imports.html
=> Update to circuit-renderer 0.9

.github/workflows/pytket_benchmarking.yml
Add release tag to slack message.
https://github.com/CQCL-DEV/pytket-benchmarking/issues/206
=> ci: Add release version to slack message

pytket/pytket/circuit/display/static/head_imports.html
Update link for circuit renderer css file - fixes rendering bug due to mismatched versions.
n/a
=> circuit-display: update css file to v0.9

pytket/docs/changelog.rst, pytket/docs/conf.py
=> release 1.31.1

.github/workflows/build_and_test.yml, pytket/pytket/circuit/logic_exp.py
Closes #1626 .
Drive-by: mypy fix for mypy 1.12.1.
(Please ignore nix build error due to older mypy version.)
=> Don't try to install pytket[ZX] with Python 3.13.

pytket/binders/circuit/clexpr.cpp, pytket/docs/circuit.rst, pytket/docs/circuit_class.rst, pytket/pytket/_tket/circuit.pyi
See #1654 (will add json schema in a separate PR).
=> Document ClExpr and friends.

.github/workflows/pytket_benchmarking.yml
Fixes error from moving to slack-github-action v2.0.0
N/A
=> ci: Update to slack github action v2

pytket/docs/changelog.rst
Oops, I should have done this before the release.
=> Update changelog for 1.35.0 release.

pytket/docs/poetry.lock, pytket/docs/pyproject.toml
Updating docmain for the change in https://github.com/CQCL/tket/pull/1711
=> Update sphinx dependency on `docmain`

pytket/binders/predicates.cpp, pytket/conanfile.py, pytket/docs/changelog.rst, tket/conanfile.py, tket/src/Predicates/Predicates.cpp, tket/test/src/test_CompilerPass.cpp
=> Make CliffordCircuitPredicate accept measurements

pytket/docs/changelog.rst, pytket/pytket/qasm/qasm.py, pytket/tests/qasm_test.py
=> Fix conversion of CnX to QASM

pytket/binders/circuit/main.cpp, pytket/binders/passes.cpp, pytket/docs/changelog.rst, pytket/pytket/_tket/circuit.pyi, pytket/pytket/_tket/passes.pyi, pytket/pytket/_tket/predicates.pyi, pytket/pytket/utils/operators.py
Including inserting some narrow non-breaking spaces to keep sphinx happy.
=> Minor docs cleanup.

pytket/binders/circuit/Circuit/main.cpp, pytket/docs/changelog.rst, pytket/pytket/_tket/circuit.pyi, pytket/tests/add_circuit_test.py
=> Add `Circuit.add_circuit_with_map()` method

pytket/docs/circuit_class.rst, pytket/tests/backend_test.py
Drive-by: Fix mypy issues following update of mypy to 1.15.0.
=> Add `Circuit.add_circuit_with_map()` to docs.

pytket/pytket/logging/__init__.py
=> Ignore ruff warning.

pytket/conanfile.py, pytket/docs/changelog.rst, tket/conanfile.py, tket/src/PauliGraph/PauliGraph.cpp, tket/src/Predicates/PassGenerators.cpp, tket/test/src/test_CompilerPass.cpp
=> Make `PauliSimp` accept circuits with SX and SXdg gates

.github/workflows/build_and_test.yml, pytket/pytket/_tket/circuit.pyi
Not sure how long this has not been working for. Need to pass `--exit-code` to `git diff` in order for the return value to be non-zero if anything has changed.
=> Fix stub check

pytket/pytket/_tket/architecture.pyi, pytket/pytket/_tket/circuit.pyi, pytket/pytket/_tket/logging.pyi, pytket/pytket/_tket/mapping.pyi, pytket/pytket/_tket/partition.pyi, pytket/pytket/_tket/passes.pyi, pytket/pytket/_tket/pauli.pyi, pytket/pytket/_tket/placement.pyi, pytket/pytket/_tket/predicates.pyi, pytket/pytket/_tket/tableau.pyi, pytket/pytket/_tket/tailoring.pyi, pytket/pytket/_tket/transform.pyi, pytket/pytket/_tket/unit_id.pyi, pytket/pytket/_tket/zx.pyi, pytket/stub_generation/regenerate_stubs
Necessary after update to pybind11-stubgen 2.5.3.
=> Update stub-generation script and regenerate stubs

libs/tktokenswap/conanfile.py, libs/tktokenswap/test/conanfile.py, libs/tkwsm/conanfile.py, libs/tkwsm/test/conanfile.py
=> Update libs to boost 1.87.0

pytket/binders/circuit/classical.cpp, pytket/docs/changelog.rst, pytket/pytket/_tket/circuit.pyi, pytket/tests/classical_test.py
=> Add `MultiBit.multiplier` property

pytket/conanfile.py, pytket/docs/changelog.rst, tket/conanfile.py, tket/src/Predicates/PassLibrary.cpp, tket/test/src/ZX/test_ZXSimp.cpp
=> Preserve circuit name in `ZXGraphlikeOptimisation` pass

pytket/conanfile.py, pytket/docs/changelog.rst, pytket/tests/passes_serialisation_test.py, schemas/compiler_pass_v1.json, tket/conanfile.py, tket/src/Predicates/CompilerPass.cpp
=> Enable deserialization of `NormaliseTK2` pass

pytket/binders/architecture.cpp, pytket/docs/changelog.rst, pytket/pytket/_tket/architecture.pyi, pytket/tests/architecture_test.py
=> Enable pickling of `Architecture` objects

pytket/docs/changelog.rst
=> Release pytket 2.3.0

pytket/CMakeLists.txt, pytket/binders/architecture.cpp, pytket/binders/circuit/Circuit/add_classical_op.cpp, pytket/binders/circuit/Circuit/add_op.cpp, pytket/binders/circuit/Circuit/main.cpp, pytket/binders/circuit/boxes.cpp, pytket/binders/circuit/classical.cpp, pytket/binders/circuit/main.cpp, pytket/binders/include/add_gate.hpp, pytket/binders/include/deleted_hash.hpp, pytket/binders/include/nanobind-stl.hpp, pytket/binders/include/typecast.hpp, pytket/binders/mapping.cpp, pytket/binders/partition.cpp, pytket/binders/passes.cpp, pytket/binders/pauli.cpp, pytket/binders/placement.cpp, pytket/binders/predicates.cpp, pytket/binders/tableau.cpp, pytket/binders/tailoring.cpp, pytket/binders/transform.cpp, pytket/binders/unitid.cpp, pytket/binders/zx/diagram.cpp
Hopefully this will avoid further accidents.
=> Include all nanobind/stl headers in each binder file.

pytket/conanfile.py, pytket/docs/changelog.rst, pytket/tests/circuit_test.py, tket/conanfile.py, tket/include/tket/Circuit/Circuit.hpp, tket/src/Circuit/basic_circ_manip.cpp
=> Move special `OpType` handling so that it is always applied

pytket/pytket/backends/backendresult.py, pytket/tests/predicates_test.py
This workaround fixes the issue with result handling that is causing a couple of pytket-qiskit tests to fail.
I am not sure what the proper fix should be.
=> Work around #1880 .

.github/workflows/build-without-conan.yml, build-without-conan.md
Tested [here](https://github.com/CQCL/tket/actions/runs/14727827714).
=> Fix no-conan build scripts

pytket/binders/predicates.cpp, pytket/docs/changelog.rst, pytket/tests/predicates_test.py
=> Make sure `UnitID` downcaster is included in the necessary file

pytket/docs/changelog.rst, pytket/pytket/circuit/logic_exp.py, pytket/pytket/qasm/qasm.py, pytket/tests/qasm_test.py
=> Accept length-1 bit registers as bits in QASM expressions

pytket/pytket/passes/passselector.py, pytket/ruff.toml, pytket/tests/passes_serialisation_test.py
=> update ruff python version to 3.10

.github/workflows/pytket_benchmarking.yml
This runs the newest PDF generation script form pytket-benchmarking and sends the PDF to tket slack channel.
I also tried the `files.uploadV2` method using `slackapi/slack-github-action@v2.0.0`, but the current approach provides more detailed error messages.
=> Update CI benchmarking script

.github/workflows/pytket_benchmarking.yml
=> ci: Use artifactory to install pytket-benchmarking

pytket/binders/circuit/Circuit/main.cpp, pytket/conanfile.py, pytket/docs/changelog.md, pytket/pytket/_tket/circuit.pyi, pytket/tests/transform_test.py, tket/conanfile.py, tket/include/tket/Circuit/Circuit.hpp, tket/src/Circuit/macro_manipulation.cpp, tket/src/Transformations/CliffordOptimisation.cpp, tket/src/Transformations/CliffordReductionPass.cpp, tket/test/src/Circuit/test_Boxes.cpp, tket/test/src/Circuit/test_Circ.cpp, tket/test/src/Simulation/test_CircuitSimulator.cpp, tket/test/src/test_CompilerPass.cpp, tket/test/src/test_PhasePolynomials.cpp
=> Add return value for `Circuit::replace_SWAPs()`, and use it

pytket/binders/circuit_library.cpp, pytket/conanfile.py, pytket/docs/changelog.md, pytket/docs/circuit_library.md, pytket/pytket/_tket/circuit_library.pyi, pytket/pytket/circuit_library/__init__.py, pytket/tests/predicates_test.py, tket/conanfile.py, tket/include/tket/Circuit/CircPool.hpp, tket/src/Circuit/CircPool.cpp, tket/src/Predicates/PassGenerators.cpp, tket/test/src/test_CompilerPass.cpp
=> Add `tk1_to_PhasedX` and use in `AutoRebase`.

pytket/binders/passes.cpp, pytket/conanfile.py, pytket/docs/changelog.md, pytket/pytket/_tket/passes.pyi, pytket/tests/predicates_test.py, schemas/compiler_pass_v1.json, tket/conanfile.py, tket/include/tket/Predicates/PassLibrary.hpp, tket/src/Predicates/CompilerPass.cpp, tket/src/Predicates/PassLibrary.cpp, tket/test/src/test_CompilerPass.cpp, tket/test/src/test_json.cpp
=> Add `RxFromSX` pass

pytket/binders/circuit/main.cpp, pytket/docs/changelog.md, pytket/pytket/_tket/circuit.pyi, pytket/tests/predicates_test.py
=> Bind all `OpType`s

pytket/docs/extensions.md
=> Fix docs link.

pytket/docs/changelog.md
=> Update changelog for 2.9.2 release
