CQCL/tket

- pytket/pyproject.toml
- pytket/setup.py
Add `tool.setuptools_scm` section and simplify.
Release workflow tested here: https://github.com/CQCL/tket/actions/runs/1244904528
> Use `pyproject.toml` (PEP 517, 518) instead of deprecated `setup_requires`.

- .github/workflows/release.yml
This is the last "good" tag. The following commit broke our wheels:
https://github.com/pypa/manylinux/commit/1f0eec43eed0de2b7a8aa783d13b1c15840481c7
Fixes https://github.com/CQCL/pytket/issues/106.
This is not a long-term solution, but allows us to make a working release again.
> Build Linux wheels using `manylinux2014_x86_64:2021-08-01-bce1ff9`.

- .github/workflows/build_macos_m1_wheel
- .github/workflows/build_macos_wheel
- .github/workflows/linuxbuildwheel
- .github/workflows/release.yml
This is necessary even when we use a `pyproject.toml` file, as explained here: https://github.com/pypa/setuptools_scm/issues/386.
> Install `setuptools_scm` before building wheels.

- pytket/docs/changelog.rst
- pytket/pytket/backends/backend.py
- pytket/pytket/utils/expectations.py
- pytket/tests/backend_test.py
- pytket/tests/utils_test.py
I am currently making the necessary changes to pytket-extensions
> [refactor] Removed Backend.get_<data> methods

- tket/tket_deps
This ensures new components always get picked up by the script without having to be manually added.
> Get list of components programmatically in dependency graph generator.

- .github/workflows/build_and_test.yml
- .github/workflows/release.yml
- README.md
Closes #84 .
Build missing packages locally on MacOS. Cache conan data so we don't have to do this every time.
> Use apple-clang 13

- pytket/binders/passes.cpp
> Fix docs formatting for `AASRouting`.

- .github/workflows/release.yml
Closes #114 .
This is difficult to properly test without doing a pre-release, but it seems to be a pattern used in other projects; the YAML [passed](https://github.com/CQCL/tket/actions/runs/1471152587) the syntax check; and I will do a pre-release afterwards to check.
> Don't publish docs for prereleases.

- .github/workflows/build_and_test.yml
- .github/workflows/coverage.yml
- .github/workflows/linuxbuildwheel
- .github/workflows/pytket_docs.yml
- .github/workflows/release.yml
- README.md
- recipes/symengine/conanfile.py
- recipes/tket/conanfile.py
This is in order to pick up the fixes from https://github.com/symengine/symengine/pull/1849, which unblock a few other things.
The conanfile is based on the one we used to have in the CQCL-DEV/tket repo, but with some improvements (like the addition of options) from the one in the conan-center, and a more recent boost version (same as tket requires). I am not sure why we can't just use the one in the conan-center but it gave me some obscure boost linkage errors when built locally.
We should be able to revert this after the next release of symengine is uploaded to conan-center.
> Build symengine locally

- .github/workflows/build_and_test.yml
- .github/workflows/linuxbuildwheel
- .github/workflows/pytket_docs.yml
- .github/workflows/release.yml
- README.md
- pytket/CMakeLists.txt
- pytket/conanfile.txt
- recipes/pybind11/conanfile.py
Because of an unfortunate [issue](https://github.com/conan-io/conan-center-index/issues/6605) with the pybind11 conan package we have to use a local recipe to install the pybind11 package.
Release workflow tested [here](https://github.com/CQCL/tket/actions/runs/1504692592).
> Update to pybind11 2.8.1.

- .github/workflows/build_and_test.yml
- .github/workflows/release.yml
Necessary because there is no version for apple-clang 13 on the remote.
I don't really know why this didn't fail before but I suspect a combination of cache weirdness and the unsetting of `revisions_enabled` in the conan config from https://github.com/CQCL/tket/pull/138.
> Install boost on MacOS.

- .gitignore
- pytket/pyproject.toml
- pytket/pytket/__init__.py
- pytket/setup.py
Fixes [TKET-1603](https://cqc.atlassian.net/browse/TKET-1603?atlOrigin=eyJpIjoiNWRiMGU4ZDA0ZGI0NDI1YmJlN2ZiNWM5MjU5ZjM1NzEiLCJwIjoiaiJ9).
This PR addresses the report of the `pytket` version at runtime when query `pytket.__version__`. It uses `dunamai` as a runtime dependency to query `git` source tree.
> [TKET-1603] Version report

- README.md
Fixes [TKET-1720](https://cqc.atlassian.net/browse/TKET-1720?atlOrigin=eyJpIjoiMTI4NTI3MTI4ZmU5NDA3OWFiODI0MTFkYzc4ZjI0MzUiLCJwIjoiaiJ9). 
Instructions to add a link to local `pybind11` recipe.
> Add instructions to link to local `pybind11` recipe.

- tket/src/Circuit/Circuit.hpp
- tket/src/Circuit/macro_manipulation.cpp
- tket/src/Converters/PhasePoly.cpp
- tket/tests/test_PhasePolynomials.cpp
Fixes: [TKET-1653] No wireswap handling in the creation of a phase poly box #126
I have decided to add this in the creation of the phase poly box to make sure it is not used in other cases. This is probably very inefficient in other cases, the efficient solution is found in the decomposition of the ppb.
> fix wire swap handling in the creation of a phase poly box [TKET-1653]

- pytket/tests/backend_test.py
- pytket/tests/classical_test.py
Fixes [TKET-1669](https://cqc.atlassian.net/browse/TKET-1669?atlOrigin=eyJpIjoiMjkwNWFlMmZiOTExNGE1MTk5MjMzOTE0YjFhNzM4YjMiLCJwIjoiaiJ9).
This PR addresses CI timeouts that cause hypothesis test failures. Following the recommendation, I added a deadline to `None` in the `@settings` to disable the 200 ms timeout as documented [here](https://hypothesis.readthedocs.io/en/latest/settings.html).
> [TKET-1669] Setting deadlines to None to avoid timeouts.

- pytket/binders/circuit/main.cpp
- pytket/tests/circuit_test.py
Fixes [TKET-1670](https://cqc.atlassian.net/browse/TKET-1670?atlOrigin=eyJpIjoiM2ViZTZjNWQ4MmY3NGQwYThjMTQ4MThkNTAwMzM3NWYiLCJwIjoiaiJ9).
This PR addresses exposing the `free_symbols` method from the underlying gate at the op level in Python. 
It also adds an `pybind11` custom exception to be thrown in Python if the method is not defined for that gate. 
However, local checks return an empty set in that case.
> [TKET-1670] Expose free symbols

- .github/workflows/lint.yml
1. To avoid unnecessary checks when pushing to private branches.
2. So that it is triggered when we get external PRs from forks.
> Run lint check on pull request rather than push.

- pytket/pytket/qasm/qasm.py
- pytket/tests/qasm_test.py
- pytket/tests/qasm_test_files/test16.qasm
Context: https://github.com/Qiskit/qiskit-terra/pull/4765
Before this change the following code would fail
```py
from pytket.qasm import circuit_from_qasm_str
from qiskit import QuantumCircuit
qc = QuantumCircuit(1)
qc.p(0, 0)
qc.u(0, 0, 0, 0)
print(circuit_from_qasm_str(qc.qasm()))
```
With a message like: `pytket.qasm.qasm.QASMParseError: Cannot parse gate of type: p`
> Add u and p gate aliases to match updated qelib1.inc

- .github/workflows/build_and_test.yml
- .github/workflows/release.yml
- pytket/CMakeLists.txt
- recipes/symengine/conanfile.py
- recipes/tket/conanfile.py
- recipes/tket/patches/vf2_sub_graph_iso.diff
- recipes/tket/test_package/CMakeLists.txt
- tket/proptests/CMakeLists.txt
- tket/src/ArchAwareSynth/CMakeLists.txt
- tket/src/Architecture/CMakeLists.txt
- tket/src/Characterisation/CMakeLists.txt
- tket/src/Circuit/CMakeLists.txt
- tket/src/Clifford/CMakeLists.txt
- tket/src/Converters/CMakeLists.txt
- tket/src/Diagonalisation/CMakeLists.txt
- tket/src/Gate/CMakeLists.txt
- tket/src/Graphs/CMakeLists.txt
- tket/src/MeasurementSetup/CMakeLists.txt
- tket/src/OpType/CMakeLists.txt
- tket/src/Ops/CMakeLists.txt
- tket/src/PauliGraph/CMakeLists.txt
- tket/src/Predicates/CMakeLists.txt
- tket/src/Program/CMakeLists.txt
- tket/src/Routing/CMakeLists.txt
- tket/src/Simulation/CMakeLists.txt
- tket/src/Transformations/CMakeLists.txt
- tket/src/Utils/CMakeLists.txt
- tket/src/ZX/CMakeLists.txt
- tket/tests/CMakeLists.txt
A few changes are rolled together here:
* Update to boost 1.78.0.
* Install boost with all-default options on M1. (Previous build issues seem to have been fixed.)
* Specify target link libraries explicitly, rather than using `CONAN_LIBS` which includes many unnecessary libraries.
* Remove restriction on build parallelism on Windows.
* Eliminate the dependency on `boost::chrono` by modifying our boost patch to use `std::chrono`. (The original version used `boost::chrono` because it was intended as a patch to boost, which needs to build without `std::chrono`, but that PR has since been dropped and replaced by another one without this dependency.)
> Explicit linking of library dependencies

- pytket/docs/index.rst
- pytket/docs/tableau.rst
Forgot to update the docs with #151 . My bad
> Add pytket.tableau to API docs

- tket/src/Predicates/PassGenerators.cpp
- tket/src/Predicates/PassLibrary.cpp
- tket/src/Predicates/include/Predicates/PassGenerators.hpp
- tket/src/Transformations/Decomposition.cpp
- tket/tests/test_CompilerPass.cpp
This is fixing https://github.com/CQCL/tket/issues/97
The problem has been a wrong handling of the implicit wire swaps in the aas pass
> [TKET-1598] fix ConnectivityPredicate fails after FullPeepholeOptimise and AASRouting

- .github/workflows/build_and_test.yml
- .github/workflows/linuxbuildwheel
- README.md
- pytket/CMakeLists.txt
- recipes/tket/conanfile.py
- recipes/tket/test_package/CMakeLists.txt
- tket/proptests/CMakeLists.txt
- tket/src/Utils/CMakeLists.txt
- tket/tests/CMakeLists.txt
Go back to using the library version of spdlog/fmt, except when building Linux wheels.
This mostly reverts #44 . It should make builds a bit faster, and _may_ solve #178 (we'll see).
> Use spdlog library

- pytket/binders/circuit/main.cpp
- pytket/pytket/backends/backendinfo.py
- pytket/tests/backendinfo_test.py
- pytket/tests/strategies.py
This partially addresses #192 . The remaining issue is for the `misc` field, which is https://github.com/CQCL/pytket-extensions/issues/288 .
> Ensure that the standard fields of `BackendInfo` are JSON-serializable

- pytket/binders/routing.cpp
- tket/src/Circuit/basic_circ_manip.cpp
- tket/src/Circuit/include/Circuit/Circuit.hpp
- tket/src/Predicates/CompilationUnit.cpp
- tket/src/Predicates/CompilerPass.cpp
- tket/src/Predicates/PassGenerators.cpp
- tket/src/Predicates/PassLibrary.cpp
- tket/src/Predicates/include/Predicates/CompilationUnit.hpp
- tket/src/Routing/Placement.cpp
- tket/src/Routing/Routing.cpp
- tket/src/Routing/include/Routing/Placement.hpp
- tket/src/Routing/include/Routing/Routing.hpp
- tket/src/Transformations/Combinator.cpp
- tket/src/Transformations/include/Transformations/Transform.hpp
- tket/src/Utils/include/Utils/UnitID.hpp
- tket/tests/test_CompilerPass.cpp
> Move "unit bimaps" out of the `Circuit` class and let `Transform` handle them.

- recipes/tket/conanfile.py
- recipes/tket/test_package/conanfile.py
Copy `.dll` files to `bin` directory on Windows.
This makes the recipe compliant with conan-center packaging rules (verified using https://github.com/conan-io/hooks/blob/master/hooks/conan-center.py ).
> Simplify conanfile in test package

- .gitattributes
- .github/workflows/build_and_test.yml
- .github/workflows/build_symengine.yml
- .github/workflows/coverage.yml
- .github/workflows/linuxbuildwheel
- .github/workflows/pytket_docs.yml
- .github/workflows/release.yml
- README.md
- recipes/tket/conanfile.py
The plan is to have tket components individually versioned, packaged and hosted on tket.jfrog.io in a new `tket-conan` repository. This should help make tket more modular and extensible, as well as reducing build times.
As a "warm-up", and to save having to build symengine on the CI, I have:
* added a workflow that builds symengine (from our own recipe) and uploads the packages to `tket-conan`, in several configurations (4 platforms x Release/Debug x shared/static);
* changed the CI workflows that build tket so that they can just download symengine from the new remote instead of having to build it;
* added the necessary credentials as github secrets;
* run the workflows, to test them and populate the repository.
The `build_symengine` workflow is run only for PRs and pushes to `develop` …
> Add new conan remote and use pre-built symengine package

- pytket/tests/circuit_test.py
- tket/src/Circuit/Circuit.cpp
- tket/src/Gate/Rotation.cpp
- tket/src/Utils/Expression.cpp
- tket/src/Utils/include/Utils/Expression.hpp
> Don't assume expressions being substituted are mod 4

- .github/workflows/linuxbuildwheel
Manylinux uses a different `compiler.libcxx` so there isn't a pre-built version available (currently).
> Build symengine on manylinux.

- pytket/docs/changelog.rst
- pytket/pytket/backends/backend.py
- pytket/pytket/tailoring/__init__.py
After merging this I'll make a pytket pre-release and then update the extensions.
> Remove `Backend.characterisation`

- .github/workflows/release.yml
I made an error updating the release workflow when we upgraded Python versions.
> Don't build 3.9 wheels twice on MacOS.

- pytket/binders/circuit/Circuit/add_classical_op.cpp
- pytket/binders/circuit/Circuit/add_op.cpp
- pytket/binders/circuit/boxes.cpp
- pytket/binders/circuit/main.cpp
- pytket/binders/zx/diagram.cpp
- pytket/docs/changelog.rst
1. Fixed the return type of `add_op` and other methods of `pytket.Circuit` to return `self` as advertised in the docs.
2. Removed default values for arguments `minval` and `maxval` of `add_c_range_predicate`.
> [bugfix] small API fixes in `pytket.Circuit`

- .github/workflows/build_macos_m1_wheel
- .github/workflows/build_macos_wheel
- .github/workflows/linuxbuildwheel
- .github/workflows/release.yml
- pytket/pyproject.toml
- pytket/setup.py
Use the recommended `python -m build` instead when building wheels.
Tested [here](https://github.com/CQCL/tket/actions/runs/1891988648).
Closes #112 .
> Don't invoke `setup.py` directly

- tket/tests/CMakeLists.txt
- tket/tests/tkettestsfiles.cmake
- tket/tests/tkettestutilsfiles.cmake
I often find myself removing irrelevant tests from my local `tkettestsfiles.cmake` to speed up testing. However it often happens that I delete necessary test utilities in the process, as it is currently hard to distinguish them from ordinary test cases in the list of files. This causes annoying compilation errors and requires me to manually add back entries to the list of files.
I suggest to solve this problem by putting all the test utilities in a separate `tkettestutilsfiles.cmake` file. These group all the files that do not have any `SCENARIO` test cases inside them and are merely used through `#include`s in other test files.
Ideally, I would have explicit dependencies between tests and the utilities they depend on, so that we would only compile the required utilities. However I don't …
> [infra] Separated test utils from tests

- tket/src/Utils/Expression.cpp
- tket/tests/Circuit/test_Boxes.cpp
Even though non-physical, there is no reason to disallow non-real parameters in operations. The current code already allows such operations to be included in circuits; the problem is that it then throws exceptions when evaluating them. This patch catches those exceptions, so that `eval_expr()` returns `std::nullopt` as expected.
> Handle non-real non-symbolic expressions in eval_expr()

- pytket/docs/changelog.rst
- tket/src/Predicates/Predicates.cpp
- tket/tests/test_Predicates.cpp
> Check for isolated nodes in `ConnectivityPredicate::implies()`

- tket/src/Predicates/PassGenerators.cpp
Generic routing doesn't require all logical qubits to be assigned to architecture qubits, it can dynamically assign them.
> Remove PlacementPredicate from routing_pass

- pytket/docs/changelog.rst
- pytket/pytket/utils/operators.py
- pytket/tests/qubitpaulioperator_test.py
> Sort qubit list when computing matrix without user-supplied list.

- pytket/setup.py
Fixes #299 .
The "conan info" command may print informational messages to stdout, in particular about use of compatible packages. Obviously this makes the output invalid json.
This started happening with some recent updates to how conan handles apple-clang versions "13" and "13.0".
Couldn't get the tempfile solution to work on Windows so resorted to a fixed filename.
> Write conan info to file instead of stdout.

- .github/workflows/coverage.yml
- README.md
- recipes/tket-tests/conanfile.py
- recipes/tket-tests/test_package/conanfile.py
- tket/tests/CMakeLists.txt
- tket/tests/Circuit/test_Circ.cpp
- tket/tests/Placement/test_Placement.cpp
- tket/tests/TokenSwapping/TableLookup/test_SwapSequenceReductions.cpp
- tket/tests/TokenSwapping/test_BestTsaFixedSwapSequences.cpp
- tket/tests/test_AASRoute.cpp
- tket/tests/test_ControlDecomp.cpp
- tket/tests/test_LexiRoute.cpp
- tket/tests/test_RoutingPasses.cpp
- tket/tests/test_SteinerForest.cpp
This PR is a refactoring of the current tests and CI so those tests that have a running time >= 1 second (on a regular modern laptop) are executed only once a week. It includes the following changes:
- The long tests have the `"[.long]"` tag, which means that they are by default _hidden_, and can be run by specifying the `"[long]"` tag to the test_tket binary. **NOTE:** making a scenario hidden has the side-effect that its tags are not reported if you run the catch2 binary with `-t` to list the tags. 
- Remove the `TKET_TESTS_FULL` compilation flag so now all the tests are built at once.
- Refactor some of the tests so only the long running `GIVEN` cases are assigned the `"[.long]"` flag.
- Add the `tket-tests:long` option to run only the long tests.
- Change the coverage.yml to generate …
> [TKET-1913] Refactor long running tests

- .github/workflows/coverage.yml
Works around incompatibility between gcovr 5.0 and jinja2 3.1.0 (see https://github.com/CQCL/tket/runs/5688235924 for error).
> Pin jinja2 and gcovr versions.

- .github/workflows/build_symengine.yml
- .github/workflows/linuxbuildsymengine
- .github/workflows/linuxbuildwheel
Note, packages have been uploaded already, by [this](https://github.com/CQCL/tket/actions/runs/2109259738) test run.
Release workflow using prebuilt package: https://github.com/CQCL/tket/actions/runs/2109353901
> Use prebuilt symengine for release builds

- .github/workflows/build_spdlog.yml
- .github/workflows/linuxbuildspdlog
- recipes/spdlog/CMakeLists.txt
- recipes/spdlog/conandata.yml
- recipes/spdlog/conanfile.py
Follows the pattern of the symengine workflow.
This version of `spdlog` differs from the version on conan-center in that it does not have `fmt` as an external dependency.
In a [follow-up PR](https://github.com/CQCL/tket/pull/323) I will make tket depend on this version.
> Upload spdlog package to tket/stable

- tket/src/Circuit/CircPool.cpp
- tket/tests/Circuit/test_Circ.cpp
When the rotation angle is pi mod 2pi, the `CRx`, `CRy` and `CRz` optypes can be decomposed using a single CX gate.
> [feature] Decompose CRx/y/z using 1xCX if possible

- pytket/setup.py
This allows us to use more recent versions of some of the typing modules, e.g. `boto3-stubs`.
> Update `typing-extensions` dependency.

- pytket/binders/architecture.cpp
- pytket/binders/placement.cpp
- pytket/tests/placement_test.py
Despite being imported from `pytket.architecture`, `FullyConnected` is not an `Architecture` object and so cannot be used with `Routing` and `Placement` methods. 
This PR makes this clear via updating the docs. It also adds a basic new method to `pytket.placement`, `place_fully_connected`, for automatically reassigning `Circuit` `Qubit` to `FullyConnected` `Node`.
> [TKET-1958] Update `FullyConnected` docs and add `place_fully_connected`

- tket/src/Transformations/PhasedXFrontier.cpp
I think this should fix the valgrind issue.
> Construct a new `OptVertex` when populating `vertices`.

- .github/workflows/build_symengine.yml
- recipes/symengine/conanfile.py
Will follow-up with a TKET PR to use this version of symengine and boost, which will allow us to drop one of our build-time patches (already tested locally).
> Create symengine 0.9.0.1 requiring boost 1.79.0.

- pytket/binders/circuit/library.cpp
- pytket/binders/passes.cpp
- pytket/binders/transform.cpp
- pytket/docs/changelog.rst
- pytket/pytket/utils/symbolic.py
- tket/proptests/proptest.cpp
- tket/src/Circuit/CircPool.cpp
- tket/src/Circuit/CircUtils.cpp
- tket/src/Circuit/include/Circuit/CircPool.hpp
- tket/src/Circuit/include/Circuit/CircUtils.hpp
- tket/src/Predicates/CompilerPass.cpp
- tket/src/Predicates/PassLibrary.cpp
- tket/src/Predicates/include/Predicates/PassLibrary.hpp
- tket/src/Transformations/Decomposition.cpp
- tket/src/Transformations/OptimisationPass.cpp
- tket/src/Transformations/Replacement.cpp
- tket/src/Transformations/include/Transformations/Decomposition.hpp
- tket/src/Transformations/include/Transformations/OptimisationPass.hpp
- tket/src/Transformations/include/Transformations/Replacement.hpp
- tket/src/Utils/MatrixAnalysis.cpp
- tket/src/Utils/include/Utils/MatrixAnalysis.hpp
- tket/tests/Ops/test_Ops.cpp
- tket/tests/Passes/test_SynthesiseTK.cpp
- tket/tests/test_CompilerPass.cpp
- tket/tests/test_TwoQubitCanonical.cpp
- tket/tests/test_json.cpp
- tket/tests/tkettestsfiles.cmake
Add a new transform and pass to efficiently convert to the TK1/TK2 basis.
This is "best effort" at finding efficient TK2 decompositions of standard gates. I have left TODO comments where we should be able to do better but I have not been able to figure out how: I will raise a new issue for those cases.
> TK2 synthesis pass

- tket/src/Architecture/DistancesFromArchitecture.cpp
- tket/src/Architecture/include/Architecture/Architecture.hpp
- tket/src/Graphs/include/Graphs/AbstractGraph.hpp
- tket/src/Graphs/include/Graphs/CompleteGraph.hpp
- tket/src/Graphs/include/Graphs/DirectedGraph.hpp
In its underlying graph classes. The graph classes finds the graph diameter by getting the distance between every pair of nodes in the graph, tracking which is largest and then returning it. This value isn't cached, meaning every time `get_diameter` is called this process is repeated, something which is done liberally in routing and a cause of some nasty overhead. This small fix massively improves routing runtime, especially on larger connectivity graphs.
> Cache diameter returned by `Architecture::get_diameter()`

- tket/src/CMakeLists.txt
- tket/src/Graphs/GraphColouring.cpp
- tket/src/TokenSwapping/TableLookup/FilteredSwapSequences.cpp
- tket/src/Utils/include/Utils/EigenConfig.hpp
Changes:
(1) Since `tket` is compiled with `-Wall -Werror`, it will fail to compile Eigen due to this [bug](https://gitlab.com/libeigen/eigen/-/issues/2304). Hence, adding `-Wno-maybe-uninitialized` when gcc 11+ is used.
(2) gcc-11 only has changes in its [header dependency](https://gcc.gnu.org/gcc-11/porting_to.html). In particular, `<limits>` (for `std::numeric_limits`) is used less widely and needs to be included explicitly.
Tested by: compiling `tket` following the [instructions](https://github.com/CQCL/tket#how-to-build-tket-and-pytket).
> Fixes to compile with gcc-11

- pytket/binders/circuit/Circuit/add_classical_op.cpp
- pytket/binders/circuit/classical.cpp
- pytket/binders/circuit/unitid.cpp
- pytket/binders/include/UnitRegister.hpp
- pytket/pytket/circuit/decompose_classical.py
- pytket/pytket/qasm/qasm.py
- pytket/tests/classical_test.py
also contains a second driveby commit fixing a qasm output bug
> add binder functions to simplify setting and copying registers

- pytket/binders/architecture.cpp
- pytket/docs/changelog.rst
- pytket/tests/backendinfo_test.py
> [bugfix] Fix serialization of `BackendInfo` with `RingArch` and `FullyConnected` architectures.

- tket/src/Transformations/OptimisationPass.cpp
- tket/src/Transformations/Rebase.cpp
- tket/src/Transformations/include/Transformations/Rebase.hpp
- tket/tests/test_Synthesis.cpp
Fixes #394 .
Simply append a rebase and redundancy-removal to the end of the passes in question. (Rebases do handle conditionals correctly.)
As well as the `GateSetPredicate`, the `MaxTwoQubitGates` postcondition was also failing. I've added tests to ensure all postconditions are satisfied for circuits containing conditional gates and three-qubit gates.
> Ensure conditional gates are rebased in synthesis passes

- .github/workflows/test_libs.yml
This fixes one problem but not the main issues, which I am stil trying tol debug.
What I can't understand is why the build-and-test workflows are succeeding here but not on push to develop. My only idea at the moment is that we are being throttled by the artifactory for exceeding our usage limits...
Let's see if it happens again when this is merged?
> Require "changes".

- libs/tktokenswap/test/TableLookup/test_SwapSequenceReductions.cpp
Otherwise they won't run. They actually add very little to the running time of the tests.
> Remove "long" tag from tktokenswap tests.

- recipes/tket/conanfile.py
- recipes/tket/test_package/CMakeLists.txt
* Remove obsolete components from tket conanfile.
* Make the test program link to everything: this saves having to edit the dependency list whenever one wants to change the program, e.g. for debugging an issue.
> Minor clean-up

- tket/src/ArchAwareSynth/Path.cpp
- tket/src/ArchAwareSynth/SteinerForest.cpp
- tket/src/ArchAwareSynth/include/ArchAwareSynth/Path.hpp
- tket/src/ArchAwareSynth/include/ArchAwareSynth/SteinerForest.hpp
- tket/tests/test_Path.cpp
- Refactor `phase_poly_synthesis()` so that it makes use of a helper class.
- Don't call `find_hampath()` unless we need to.
- When we do need to find a Hamiltonian path, construct two circuits from it, one with the path reversed, and select the circuit of lower depth.
Fixes #412 .
> Improvements to `phase_poly_synthesis()`

- .github/workflows/compare-pytket-coverage
This PR fixes the issues with the pytket coverage checks where the random inputs generated with our `hypothesis` strategies would generate a slightly different coverage ratio.
Now, we are rounding the ratio up to 2 decimal places before comparing, so `0.8592 < 0.8601` becomes `0.86 < 0.86`.
> [fix] Check pytket coverage up to 2 decimal places

- .github/workflows/publish_tket_package.yml
- recipes/tket/conanfile.py
Workflow is triggered by a push to a branch called package/something.
Versions are built and uploaded for Linux, MacOS x86_64, MacOS arm64 and Windows; Release/Debug; static/shared. Exception: no package for MacOS (either architecture)/Debug/shared, because this causes an assertion failure in symengine when running the test program.
To see available configurations:
```shell
conan search tket/1.0.1@tket/stable -r tket-conan
```
The packages are being uploaded now: https://github.com/CQCL/tket/actions/runs/2589117597
> Add workflow to upload tket package to conan

- .github/workflows/release.yml
This platform is deprecated: https://github.com/actions/virtual-environments .
> Stop testing on MacOS 10.15.

- pytket/binders/transform.cpp
- pytket/docs/changelog.rst
- pytket/tests/backendinfo_test.py
- pytket/tests/transform_test.py
- tket/src/Circuit/Boxes.cpp
- tket/src/Circuit/ThreeQubitConversion.cpp
- tket/src/Circuit/include/Circuit/ThreeQubitConversion.hpp
- tket/src/Transformations/ThreeQubitSquash.cpp
- tket/src/Transformations/include/Transformations/ThreeQubitSquash.hpp
- tket/tests/Circuit/test_ThreeQubitConversion.cpp
The existing `three_qubit_synthesis()` method decomposes a unitary into at most 20 CX gates. I have added an analogous `three_qubit_tk_synthesis()` method that decomposes a unitary into at most 15 TK2 gates. (It may be possible to do better than this, but I don't know how. I simply took the existing steps based on the cosine--sine decomposition and modified them. I had hoped that it might be possible to use fewer gates in the `two_qubit_diag_adjoint_plex_tk()` and `two_qubit_modified_cossin_circ_tk()` subroutines, but numerical experiments suggest not.)
Decompose `Unitary3qBox` using this method.
Add an option to the `three_qubit_squash` transform (and its Python wrapper) to target TK2 instead of CX.
> Add option to `Transforms.ThreeQubitSquash` to target TK2 gates

- pytket/docs/circuit_class.rst
- pytket/pytket/circuit/add_condition.py
- pytket/pytket/circuit/decompose_classical.py
- pytket/pytket/circuit/logic_exp.py
- pytket/pytket/qasm/qasm.py
- pytket/tests/classical_test.py
This PR addresses the extension of the previous `ConstPredicate` to a more general `RegPredicate` where the operands can be either logic expressions, bits, bitregisters or constants.
> Extend reg comparison

- .github/workflows/build_and_test.yml
- .github/workflows/build_libs.yml
- .github/workflows/coverage.yml
- .github/workflows/linuxbuildlib
- .github/workflows/linuxbuildwheel
- .github/workflows/publish_tket_package.yml
- .github/workflows/release.yml
- .github/workflows/test_libs.yml
- .github/workflows/test_libs_all.yml
- .github/workflows/valgrind.yml
- README.md
- libs/README.md
- libs/tkassert/conanfile.py
- libs/tkassert/test/conanfile.py
- libs/tklog/conanfile.py
- libs/tklog/test/conanfile.py
- libs/tkrng/conanfile.py
- libs/tkrng/test/conanfile.py
- libs/tktokenswap/conanfile.py
- libs/tktokenswap/test/conanfile.py
- libs/tkwsm/conanfile.py
- libs/tkwsm/test/SolvingProblems/test_RandomGraphs.cpp
- libs/tkwsm/test/conanfile.py
- pytket/conanfile.txt
- recipes/tket/conanfile.py
Requires a small change to your conan configuration to build, as described in the README.
I have uploaded new versions of all the libraries in `libs` to the new repo, increasing the version numbers so that there can be no ambiguity if both repos are registered as remotes (though I'd recommend removing the old remote from config).
> Switch to quantinuum conan repo

- tket/src/Circuit/CircUtils.cpp
- tket/src/Circuit/ThreeQubitConversion.cpp
- tket/src/Circuit/include/Circuit/CircUtils.hpp
- tket/src/Transformations/BasicOptimisation.cpp
- tket/tests/Circuit/test_ThreeQubitConversion.cpp
Small changes that can save a CX or two in some cases when using `three_qubit_squash`.
This only applies when the decomposition targets CX gates. I think this could be generalised to work on TK2 gates, and in a wider scope. I will write some notes down and might present it once on a Friday.
> [feature] Improve ThreeQubitConversion

- tket/src/Graphs/include/Graphs/DirectedGraph.hpp
- tket/src/Placement/Qubit_Placement.cpp
- tket/tests/Graphs/test_DirectedGraph.cpp
- tket/tests/Placement/test_Placement.cpp
Currently it's possible to have an Architecture with an edge between a node to itself.
This is not something methods are designed to deal with or that we expect a realistic quantum device to need to represent.
This PR adds checks when edges are added to a Architecture and throws an error if the initialisation wants to do this.
Additionally`qubit_lines` has been updated to return an empty list if the circuit has no edges in its interaction graph.
> Prevent Architecture from having an edge between the same node

- pytket/binders/passes.cpp
- pytket/docs/changelog.rst
- tket/src/Predicates/include/Predicates/PassGenerators.hpp
- tket/src/Transformations/OptimisationPass.cpp
- tket/src/Transformations/include/Transformations/OptimisationPass.hpp
- tket/tests/test_CompilerPass.cpp
An extra `two_qubit_squash` pass is necessary after `clifford_simp` when targetting TK2.
Also, implicit swaps are never required when targetting TK2 because any such swap can be swallowed into an existing TK2. Implicit swaps would be added in further down the compilation when TK2s are further decomposed into hardware primitives.
> [bugfix] FullPeephole in TK2 mode squashes correctly

- pytket/docs/changelog.rst
- pytket/tests/transform_test.py
- tket/src/Transformations/BasicOptimisation.cpp
- tket/src/Transformations/OptimisationPass.cpp
- tket/src/Utils/MatrixAnalysis.cpp
- tket/tests/test_TwoQubitCanonical.cpp
This PR:
minor tweak to the transformations used in `FullPeepholeOptimise` when targeting CX.
1. The first `two_qubit_squash` doesn't need swaps because it can leave more optimisation opportunities to the following `clifford_simp`
2. Run `two_qubit_squash` before `three_qubit_squash`. This time swaps are allowed
small changes to `two_qubit_squash`
1. Round matrix before using SelfAdjointEigenSolver in `get_information_content`. This seems to make it easier to produce Clifford angles.
Running FullPeepholeOptimise on benchmark circuits suggests a 8% improvement in CX count and a 7% improvement in depth.
Little rounding errors might cause SelfAdjointEigenSolver to produce different Eigen vectors. However, there is a difference in quality (in terms of local rotation angles) among equivalent …
> Fix FullPeepholeOptimise regression

- pytket/pytket/circuit/display/circuit.html
When exporting jupyter notebooks as markdown, Jupyter (or pandoc presumably) preserves blank lines in the html it exports which isn't valid in a markdown file. I could try and write a fix on the jupyter repo or write a custom html parser but this is the easiest solution for now. This will help when embedding the circuit renderer on webpages when using a markdown export.
> Circuit HTML - Remove blank lines in template.

- .github/workflows/compare-coverage
- .github/workflows/coverage.yml
The latest release of [gcovr](https://github.com/gcovr/gcovr/releases/tag/5.2) fixes the issue observed when using the `--decisions` flag in the tket code base. Also, it seems the line coverage is now correctly calculated. This PR then enables the use of the `--decisions` flag with `gcovr` for creating the coverage report, and the check done in `compare-coverage` against the branches score reported.
> [test] Use --decisions flag for gcovr while generating tket coverage report

- .github/workflows/build_and_test.yml
- .github/workflows/build_libs.yml
- .github/workflows/check-tket-reqs
- .github/workflows/coverage.yml
- .github/workflows/linuxbuildwheel
- .github/workflows/publish_tket_package.yml
- .github/workflows/release.yml
- .github/workflows/valgrind.yml
- CONTRIBUTING.md
- README.md
- pytket/CMakeLists.txt
- pytket/conanfile.txt
- pytket/setup.py
- recipes/tket-proptests/conanfile.py
- recipes/tket-tests/conanfile.py
- recipes/tket/conanfile.py
- tket/src/CMakeLists.txt
This is a second attempt at #487 , which was reverted because on Linux pytket was not working when the tket package was downloaded from the repo insetad of being built locally. The reason was that the shared libraries contained hard-coded rpath information pointing to paths that were correct when they were built but are no longer correct at runtime.
The solution is to:
- move the tket libraries alongside the binder libraries in Linux builds of pytket, as we were already doing for MacOS and Windows;
- explicitly set the rpath to `${ORIGIN}` on Linux, which ensures that libraries look in the local directory for other libraries that they need to load.
> Upload tket conan packages

- pytket/conanfile.txt
- pytket/tests/transform_test.py
- recipes/tket-proptests/conanfile.py
- recipes/tket-tests/conanfile.py
- recipes/tket/conanfile.py
- tket/src/Transformations/BasicOptimisation.cpp
- tket/tests/test_Synthesis.cpp
Fixes #514 .
This is the quick fix. Of course it would be better to find the cause and fix it (so that `commute_through_multis()` can work with conditionals), but given the need for a hotfix release I propose doing this first and then coming back to it.
> Revert changes to `commute_through_multis()` to handle conditionals

- .github/workflows/build_and_test.yml
- .github/workflows/release.yml
- README.md
Forcing build of tket when `--build=missing` is used on MacOS prevents use of cached version. I think this could make a difference in cases where PRs get updated.
> Improvements to workflow and README

- pytket/setup.py
> List pytket.qasm.includes explicitly.

- .github/workflows/build_and_test.yml
- .github/workflows/build_libs.yml
- .github/workflows/publish_tket_package.yml
- .github/workflows/release.yml
- .github/workflows/test_libs.yml
- .github/workflows/test_libs_all.yml
I installed the ARM64 runner on our CI Mac Mini and added it to the repo. This updates our workflows to use it.
https://github.blog/changelog/2022-08-09-github-actions-self-hosted-runners-now-support-apple-m1-hardware/
> Use native ARM64 runner

- libs/tktokenswap/conanfile.py
- libs/tktokenswap/test/conanfile.py
- libs/tkwsm/conanfile.py
- libs/tkwsm/test/conanfile.py
I don't know why the coverage check failed; this shouldn't happen as there are no changes to the code being analysed; possibly the last report may have been uploaded in error, or gcovr has changed somehow. Anyway, I think this failure can be ignored.
PR updating tket to follow.
> Update boost version in libs.

- .github/workflows/build_and_test.yml
- .github/workflows/build_libs.yml
- .github/workflows/publish_tket_package.yml
- .github/workflows/release.yml
- .github/workflows/test_libs.yml
- .github/workflows/test_libs_all.yml
Will update names of "required" checks after merging.
Note that I have already built and uploaded windows-2022 versions of the libraries and tket itself to the artifactory:
- https://github.com/CQCL/tket/actions/runs/3067139661
- https://github.com/CQCL/tket/actions/runs/3067799640
I have also uploaded suitable versions of boost and its dependencies, and catch2, so that those don't have to be built each time. (They are not in the conan-center yet.)
> Switch to windows-2022.

- .github/workflows/build_and_test.yml
- .github/workflows/conan-setup
- .github/workflows/release.yml
- .github/workflows/test_libs.yml
- .github/workflows/valgrind.yml
As discussed [here](https://github.com/CQCL/tket/pull/529#discussion_r970694550).
The price we pay is storing the contents of `~/.conan/data/tket` in an artefact, which is then downloaded by each pytket build. But this is still a net gain in time, as well as a useful refactor.
I also factored out the script to set up the conan profile and options.
(Will require a small tweak if #540 is merged first.)
> Handle python versions in matrix.

- .github/workflows/build-symengine.yml
- .github/workflows/build_and_test.yml
- .github/workflows/build_libs.yml
- .github/workflows/publish_tket_package.yml
- .github/workflows/release.yml
- .github/workflows/test_libs.yml
- .github/workflows/test_libs_all.yml
- pytket/conanfile.txt
- recipes/symengine/all/CMakeLists.txt
- recipes/symengine/all/conandata.yml
- recipes/symengine/all/conanfile.py
- recipes/symengine/all/test_package/CMakeLists.txt
- recipes/symengine/all/test_package/conanfile.py
- recipes/symengine/all/test_package/test_package.cpp
- recipes/symengine/config.yml
- recipes/tket-proptests/conanfile.py
- recipes/tket-tests/conanfile.py
- recipes/tket/conanfile.py
Because it seems apple-clang 13.1 (macos-12) is not quite ABI-compatible with apple-clang 13.0 (macos-11), we have to build our own symengine package for this to work. I copied the recipe exactly from the conan-center, and uploaded the packages.
> Switch to macos-12

- .github/workflows/build_and_test.yml
- .github/workflows/build_libs.yml
- .github/workflows/coverage.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/publish_tket_package.yml
- .github/workflows/release.yml
- .github/workflows/test_libs.yml
- .github/workflows/test_libs_all.yml
- .github/workflows/valgrind.yml
A final (for now) round of improvements:
* Don't cache conan data on MacOS (not necessary any more, and saves time).
* Remove unused environment variable.
* Remove unnecessary fetches of whole repo history.
* Install ccache using external action.
* Update actions versions and pin marketplace actions to specific versions.
> Further workflow improvements

- .github/workflows/test_libs.yml
This PR enables the use of the `--decisions` flag for `gcovr` when generating the coverage report of the tket libs. It also changes the `test_libs.yml` workflow a bit so that all the libs are built and tested when changes to the yaml file itself are made.
> [infra] Use `gcovr --decisions` for tket libs

- .github/workflows/build-symengine.yml
- .github/workflows/build_and_test.yml
- .github/workflows/build_libs.yml
- .github/workflows/publish_tket_package.yml
- .github/workflows/release.yml
- .github/workflows/test_libs.yml
- .github/workflows/test_libs_all.yml
- README.md
- pytket/conanfile.txt
- recipes/tket-proptests/conanfile.py
- recipes/tket-tests/conanfile.py
- recipes/tket/conanfile.py
Support was added in conan version 1.53.0, released yesterday.
I have uploaded builds of the tk* libraries, symengine, boost, catch2 etc to our artifactory, so they don't have to built on each run.
> Use xcode 14 on CI

- .github/workflows/build_and_test.yml
* Correct string in condition for whether to check tket version bump. This was supposed to restrict to PRs to develop, but the syntax was wrong and so the version bump check was not being executed,
* On self-hosted (Mac M1) builds, remove the tket conan package from cache unconditionally. Otherwise, if the PR makes no changes to tket it will use whatever is in cache for the pytket build, which may not match the actual version.
> Fix two bugs in CI workflow.

- .github/workflows/build_and_test.yml
Following the suggestion here: https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
> Restrict concurrency group to pull requests.

- .github/workflows/build-external-packages
- .github/workflows/build-symengine.yml
- .github/workflows/build_and_test.yml
- .github/workflows/build_libs.yml
- .github/workflows/conan-setup
- .github/workflows/coverage.yml
- .github/workflows/linuxbuildlib
- .github/workflows/linuxbuildwheel
- .github/workflows/packages.yml
- .github/workflows/publish_tket_package.yml
- .github/workflows/test_libs.yml
- .github/workflows/test_libs_all.yml
- README.md
Currently, we have stored some packages on our artifactory for configurations that aren't built by default on conan-center (e.g. apple-clang 14, VSCode 17). This means that if a new _revision_ of a package recipe is uploaded to conan-center, until we upload the corresponding revision, our builds will fail (because they look for the most recent revision and then look for packages matching the configuration for that revision).
We solve that problem by only using our artifactory (not conan-center) during builds.
I've added a workflow script that can be used to uplaod latest revisions of any required packages. We can choose to run this if we want a newer revsion (or package version).
Another advantage is that we have control over the exact versions of all dependencies.
> Set tket-libs as the only remote.

- .github/workflows/build_and_test.yml
- .github/workflows/coverage.yml
- .github/workflows/valgrind.yml
This uses Node.js v16 so avoids the warnings we were getting from the old action using v12.
> Switch to josStorer/get-current-time.

- tket/proptests/proptest.cpp
I tripped over this while doing some build-system refactoring work.
> Fix to avoid Static Initialization Order Fiasco in proptest

- pytket/conanfile.txt
- recipes/tket-proptests/conanfile.py
- recipes/tket-tests/conanfile.py
- recipes/tket/conanfile.py
- tket/src/Converters/PauliGraphConverters.cpp
- tket/src/PauliGraph/PauliGraph.cpp
- tket/src/PauliGraph/include/PauliGraph/PauliGraph.hpp
- tket/tests/test_PauliGraph.cpp
While working on build system refactoring I encountered a mysterious segfault on Windows in the PauliGraph tests. This turned out to be due to corrupt graph iterators. The `TopSortIterator` has a raw pointer to a graph, which is only initialized when `begin()` is called and is assumed to remain valid.
I added a `PauliGraph::sanity_check()` method which provoked the segfault on Linux. This method doesn't do a great deal of sanity checking; it could be extended in the future if we wish. It's only called from the tests.
I replaced the `TopSortIterator` with `boost::topological_sort`, copying the method used in `Circuit`. The price we pay for this (in order to retain constness of other methods) is having to make `PauliGraph::graph_` an explicitly mutable member, because sorting requires …
> Replace `PauliGraph::TopSortIterator` with `boost::topological_sort`

- pytket/conanfile.txt
- pytket/tests/requirements.txt
- recipes/tket-proptests/conanfile.py
- recipes/tket-tests/conanfile.py
- recipes/tket/conanfile.py
Bumping tket version to force a new version since version 23 won't be uploaded (because of the error this is fixing...).
> Add py to list of test requirements.

- pytket/conanfile.txt
- recipes/tket-proptests/conanfile.py
- recipes/tket-tests/conanfile.py
- recipes/tket/conanfile.py
- tket/src/Placement/GraphPlacement.cpp
- tket/src/Placement/NoiseAwarePlacement.cpp
- tket/src/Placement/include/Placement/Placement.hpp
- tket/src/Predicates/PassGenerators.cpp
- tket/tests/Placement/test_GraphPlacement.cpp
We've observed before that dynamically assign Program Qubits to Architecture Nodes during routing can give an improvement in performance. In this PR I've added an extra step to the end of `GraphPlacement::get_all_placement_maps`, where it removes some Qubit->Node assignments from the constructed maps under some basic condition.
> Filter maps produced by `GraphPlacement` and `NoiseAwarePlacement` to leave some `Qubit` unassigned

- .github/workflows/build_and_test.yml
- .github/workflows/packages.yml
With the [latest macos-12 image](https://github.com/actions/runner-images/tree/macOS-12/20221027.1) it seems that Python 3.11 is the default system Python 3 and this breaks the `turtlebrowser/get-conan` action. Work around this by explicitly selecting Python 3.10 before running it.
> Select Python 3.10 before running turtlebrowser/get-conan@v1.1

- pytket/conanfile.txt
- recipes/tket-proptests/conanfile.py
- recipes/tket-tests/conanfile.py
- recipes/tket/conanfile.py
- tket/src/Placement/GraphPlacement.cpp
- tket/tests/Placement/test_GraphPlacement.cpp
There is a condition in `default_pattern_weighting` that stops `GraphPlacement` from being run on `Circuits` with multi-qubit quantum gates with more than two qubits. However, Barrier gates are multi qubit (non-quantum) gates with more than two qubits and this condition does not make a special case for them. This PR updates the condition to make sure an error isn't thrown for Barrier gates. It also makes sure that two-qubit Barrier gates aren't placed.
> Update GraphPlacement to allow Barrier gates

- .github/workflows/build_and_test.yml
- CONTRIBUTING.md
Since v14 is no longer available via homebrew.
> Update to clang-format v15

- .github/workflows/build_and_test.yml
- .github/workflows/release.yml
- pytket/pytket/utils/results.py
Although we already pass the `--doctest-modules` to pytest on the CI, no doctests are run because it is executed from the `tests` directory. We have to execute from there in order to find certain files used by the tests, so (rather than modify a lot of test code), I just added a separate step to run the doctests from the `pytket` directory.
In fact, there were no existing doctests. I added one (to show the idea). I think we should add a lot more of these. Not only do they test the code, but they improve the API documentation by giving short examples showing how the methods and classes are used:
> Run doctests

- pytket/docs/changelog.rst
- pytket/docs/utils.rst
- pytket/pytket/backends/backendresult.py
- pytket/pytket/utils/__init__.py
- pytket/pytket/utils/distribution.py
- pytket/tests/backend_test.py
- pytket/tests/distribution_test.py
@rossduncan I am adding you as a reviewer since this was mainly your request. Please let me know if you think there is essential functionality I have missed (sampling? Shannon entropy?... this sort of thing can be added if needed) -- or if I have struck the wrong level of abstraction.
Distributions can be derived from `BackendResult` objects, but you can't go back the other way. This didn't make much sense to me, since they are essentially more abstract structures and can be manipulated in ways that make reversal meaningless. Was there a concrete use case for this?
> Add utility classes for empirical and probability distributions

- pytket/tests/circuit_test.py
These tests sometimes randomly time out, causing unwanted CI failures.
> Remove deadline on tests.

- pytket/docs/changelog.rst
- pytket/pytket/backends/backend.py
This will affect the default behaviour of `get_compiled_circuit()` in all backends. It will _not_ affect the default behaviour of `default_optimisation_pass()` since that is an abstract method which is reimplemented in the backends: changing that will require changes to the individual backends.
> Make `optimisation_level` default to 2

- pytket/conanfile.txt
- pytket/docs/changelog.rst
- recipes/tket-proptests/conanfile.py
- recipes/tket-tests/conanfile.py
- recipes/tket/conanfile.py
- tket/src/Mapping/LexiRoute.cpp
- tket/src/Mapping/MappingFrontier.cpp
- tket/tests/test_LexiRoute.cpp
Basically as the name says. `MappingFrontier::add_swap` returns `false` if the vertex immediately before the proposed SWAP is an identical SWAP, thus avoiding getting stuck.
If the `false` condition is met, then the proposed SWAP is not implemented, but instead a path of SWAPs is found between one of the SWAPs in the `Node` and its target `Node` for being brought adjacent to.
During `MappingFrontier::add_swap`, if one of the `Node` "A" in the proposed SWAP between "A" and "B" is a known "ancilla node", then this `Node` "A" is removed from the "ancilla nodes container" and the `Node` "B" is added. Previously, this was incorrectly being updated before the condition for returning `false` was met. This left the "ancilla nodes container" incorrect.
A container of ancilla nodes is stored incase …
> Update `MappingFrontier::add_swap` to only edit struct attributes after any break conditions are passed

- pytket/conanfile.txt
- pytket/docs/changelog.rst
- recipes/tket-proptests/conanfile.py
- recipes/tket-tests/conanfile.py
- recipes/tket/conanfile.py
- tket/src/Circuit/CircUtils.cpp
- tket/tests/Circuit/test_Circ.cpp
- tket/tests/test_PhaseGadget.cpp
Fixes #672 .
Since this reduces branch coverage (I am not sure if I can easily reproduce it in a test), I have added a couple of unrelated edge-case tests to bring up the coverage numbers.
> Warn about rounding errors instead of asserting

- pytket/docs/changelog.rst
- pytket/pytket/qasm/qasm.py
- pytket/tests/qasm_test.py
hqs qasm header defines OpType.ZZPhase gate as "RZZ", but in converter code it's been mistakenly set to "rzz" (which is how pytket defines it as a string). This gives examples where "RZZ" is not recognised as an OpType.ZZPhase gate and so is instead read in as a custom gate.
> Update rzz qasm string in qasm converter

- pytket/conanfile.txt
- pytket/docs/changelog.rst
- recipes/tket-proptests/conanfile.py
- recipes/tket-tests/conanfile.py
- recipes/tket/conanfile.py
- tket/src/Clifford/CliffTableau.cpp
- tket/src/PauliGraph/PauliGraph.cpp
- tket/src/Predicates/PassGenerators.cpp
- tket/tests/test_CompilerPass.cpp
This was originally meant to be just adding `PhasedX` but in the process I found a few incorrect conversions among the other gates.
> Fix several incorrect gate conversions and add support for PhasedX in Pauli graph synthesis

- pytket/docs/changelog.rst
- pytket/pytket/qasm/qasm.py
- pytket/tests/qasm_test.py
This fixes two bugs:
* converting conditions defined on a strict subset of bits of a register (of a size larger than 1) to conditions on the whole register;
* ignoring the order of bits in conditions on a whole register.
In both cases, it should be possible to do the translation by being more clever. However, disallowing the conversions is better than converting them erroneously -- and matches what we were doing already in other similar situations.
> Stricter rules on conditional expressions being converted to QASM

- .github/workflows/release.yml
E.g. editing the name of a release shouldn't trigger a new build.
> Don't run release workflow when a release is edited

- .github/workflows/compare-coverage
In the compare-coverage workflow we automatically check c++ test coverage when generating pull requests to make sure that our test coverage isn't being decreased. This comprises three checks: that the percentage of number of lines of code being tested does not decrease, that the percentage of defined functions being tested does not decrease, and that the percentage of potential branches being tested does not decrease.
In practice the first of these are very helpful, or more importantly if they do decrease the generated coverage report makes it easy to spot which new lines of code aren't being tested and so to include new tests to cover them.
However, the branch coverage tests are quite unpredictable and more frequently than desirable a pull request can be made that covers all new lines of …
> Update criteria for test coverage to pass in compare-coverage

- pytket/docs/qasm.rst
- pytket/pytket/qasm/qasm.py
Updating the documentation to alert users to the fact that implicit qubit permutations are not handled by the qasm converters. Will also update the user manual in a separate PR.
> add note to qasm API documentation

- pytket/conanfile.txt
- pytket/docs/changelog.rst
- pytket/tests/predicates_test.py
- recipes/tket-proptests/conanfile.py
- recipes/tket-tests/conanfile.py
- recipes/tket/conanfile.py
- tket/src/Converters/PauliGraphConverters.cpp
- tket/src/Predicates/PassGenerators.cpp
- tket/src/Transformations/PauliOptimisation.cpp
- tket/tests/test_CompilerPass.cpp
- tket/tests/test_PauliGraph.cpp
> Make Pauli synthesis pass preserve name and allow implicit wire swaps

- .github/workflows/build_macos_m1_wheel
- .github/workflows/build_macos_wheel
- pytket/docs/changelog.rst
- pytket/docs/getting_started.rst
I think dropping support for 10.14 is OK -- we can't test it on the CI anyway.
@CalMacCQ has tested a wheel built [here](https://github.com/CQCL/tket/actions/runs/3957597044) and checked that it works.
> Support MacOS >= 11.0 on both x86_64 and arm64

- dev-tools/helper_scripts/update_tket_version.sh
- egrep has been deprecated since 2007, and throws warnings in newer versions
- The '\d' regex in grep is not standard, it throws errors in GNU grep.
- GNU sed also doesn't like spaces after the -i flag
> Fix deprecations and errors in update_tket_version script

- pytket/conanfile.txt
- recipes/tket-proptests/conanfile.py
- recipes/tket-tests/conanfile.py
- recipes/tket/conanfile.py
- tket/tests/test_LexiRoute.cpp
- In test_LexiRoute.cpp, use the macro TEST_CIRCUITS_DIR to look for test json file (as done analogously in line 1614)
- Allows test binary to be started from any directory
> Use test circuit directory macro to find test file

- pytket/binders/passes.cpp
- pytket/conanfile.txt
- pytket/docs/changelog.rst
- pytket/pytket/passes/script.py
- pytket/tests/passes_script_test.py
- pytket/tests/passes_serialisation_test.py
- recipes/tket-proptests/conanfile.py
- recipes/tket-tests/conanfile.py
- recipes/tket/conanfile.py
- schemas/compiler_pass_v1.json
- tket/src/Predicates/CompilerPass.cpp
- tket/src/Predicates/PassLibrary.cpp
- tket/src/Predicates/Predicates.cpp
- tket/src/Predicates/include/Predicates/PassLibrary.hpp
- tket/src/Transformations/MeasurePass.cpp
- tket/src/Transformations/include/Transformations/MeasurePass.hpp
- tket/tests/test_CompilerPass.cpp
- tket/tests/test_json.cpp
Adds an `allow_partial` parameter to the `DelayMeasures` pass to push the measurements as much as possible, without failing if it cannot reach the end of the circuit.
> Add a best-effort delay measures pass

- pytket/pytket/config/pytket_config.py
Omission of this caused mypy check for `asdict` to fail.
> Declare PytketExtConfig a dataclass.

- pytket/pytket/circuit/display/__init__.py
- pytket/pytket/circuit/display/static/circuit.html
- pytket/pytket/circuit/display/static/head_imports.html
Bump renderer version to 0.6
-- Edit
This PR also includes some more recent bugfixes:
- Allow resizing the circuit display container on firefox
- Display container when viewing circuit in the browser is by default smaller
> Renderer update

- .github/workflows/build_and_test.yml
When building pytket, take care to remove and rebuild pybind11 and pytket in each new python environment.
> Fix CI scripts for MacOS ARM64

- pytket/docs/requirements.txt
6.2.0 introduces a new warning causing the` build-docs` script to exit with an error:
`WARNING: The pre-Sphinx 1.0 'intersphinx_mapping' format is deprecated and will be removed in Sphinx 8. Update to the current format as described in the documentation. Hint: "intersphinx_mapping = {'<name>': ('https://docs.python.org/', None)}".https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping`
Will make a ticket to update sphinx to 6.2.0 later.
> Add sphinx version bound

- pytket/binders/circuit/Circuit/add_op.cpp
- pytket/docs/changelog.rst
I checked that there aren't any others that are missing this binder.
> Add `Circuit.TK1` and `Circuit.TK2` methods that take `Qubit` arguments

- .github/workflows/build_and_test.yml
- .github/workflows/coverage.yml
- .github/workflows/valgrind.yml
They are not much use with conan2 builds which change the package directory for every code change. (Also not convinced they were caching anything at all.)
> Remove uses of ccache on CI

- .github/workflows/build-without-conan.yml
- .github/workflows/build_and_test.yml
- .github/workflows/build_libs.yml
- .github/workflows/coverage.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/linuxbuildwheel
- .github/workflows/packages.yml
- .github/workflows/release.yml
- .github/workflows/test_libs.yml
- .github/workflows/test_libs_all.yml
- .github/workflows/valgrind.yml
- .pre-commit-config.yaml
- pytket/pyproject.toml
- allows to trigger workflow from the github UI on any branch (without needing to open a PR and run other workflows)
- I left out issue.yml,  didn't seem necessary...
- Can't actually trigger manually until this is merged I think
- Drive-By: Pin Conan version to 2.0.5 or lower, Conan 2.0.6 breaks pytket installs (with pip) and the `rootpath` script
> Add workflow dispatch to workflows

- libs/tktokenswap/conanfile.py
- libs/tktokenswap/test/conanfile.py
- libs/tkwsm/conanfile.py
- libs/tkwsm/test/conanfile.py
Once merged we can update tket to depend on these versions and boost 1.82.0.
> Make new versions of tktokenswap and tkwsm depending on boost 1.82.0

- pytket/docs/conf.py
- pytket/docs/requirements.txt
Make sphinx generate documentation for Python Enum values. It is not currently doing so.
Before:
After:
> Generate documentation for enums

- pytket/docs/conf.py
links to the source from the pytket API docs. Only works for pure python modules currently.
Done using the [sphinx.ext.viewcode](https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html) extension
> add links to source code from API docs

- pytket/docs/changelog.rst
Also covers new Box definitions.
> Update changelog to reflect `PauliExponentials` pass

- pytket/pytket/circuit/display/__init__.py
Revert added file dump for circuits on default render. Not sure how the actual issue it was intended to fix was fixed, but I couldn't reproduce the problem (rendering large circuits having truncated iframe srcdoc).
Also add in system theme option to the renderer defaults.
> add render option, remove sleep

- .github/workflows/release.yml
- pytket/docs/changelog.rst
This addresses #926 for x86-based Macs (confirmed by Charlie). I don't know why!
Not suggesting we go back to officially supporting MacOS 10.14 (but these wheels are confirmed to work at least on MacOS 11, 12 and 13).
> Downgrade version in WHEEL_PLAT_NAME for macosx x86_64

- pytket/docs/changelog.rst
- pytket/pytket/passes/auto_rebase.py
This simple change ensures that when `ZZMax` and `ZZPhase` are both available the rebase pass chooses `ZZPhase`, which is generally a better choice.
> Give higher priority to `ZZPhase` when using `auto_rebase_pass()`

- .github/workflows/build_and_test.yml
- .github/workflows/build_libs.yml
- .github/workflows/coverage.yml
- .github/workflows/linuxbuildlib
- .github/workflows/linuxbuildpackages
- .github/workflows/linuxbuildwheel
- .github/workflows/release.yml
- .github/workflows/test_libs.yml
- .github/workflows/test_libs_all.yml
- .github/workflows/valgrind.yml
- pytket/pyproject.toml
Phew, that's a lot of lines that need changing.
This is a temporary fix because the upgrade to 2.0.8 meant conan couldn't find some expected packages on the artifactory server because they have `fPIC` in their `[options]`. It looks like [this commit](https://github.com/conan-io/conan/pull/14194) may be the cause.
We should upload new versions of the dependencies and then this issue should go away.
> Pin conan version to 2.0.7.

- .github/workflows/build_and_test.yml
- .github/workflows/build_libs.yml
- .github/workflows/coverage.yml
- .github/workflows/linuxbuildlib
- .github/workflows/linuxbuildpackages
- .github/workflows/linuxbuildwheel
- .github/workflows/release.yml
- .github/workflows/test_libs.yml
- .github/workflows/test_libs_all.yml
- .github/workflows/valgrind.yml
- pytket/conanfile.py
- pytket/pyproject.toml
- tket/conanfile.py
This reverts commit c5ef1e9826b141c8e0dfc367955ceeba0baa2b79.
I uploaded new packages built with conan 2.0.8.
Also add `--build=missing` flag back to the coverage build. (I am not actually sure why this particular build can't find a matching gmp binary.)
> Revert "[infra] Pin conan version to 2.0.7. (#937)"

- pytket/conanfile.py
- pytket/tests/placement_test.py
- tket/conanfile.py
- tket/src/Placement/NoiseAwarePlacement.cpp
Fixes https://github.com/CQCL/tket/issues/943.
There are some cases where bi-directional edges with different error rates, both >= 1, can be given a "good" cost value, when they actually correspond to bad assignments. This PR updates the cost to only includes edges with < 1 error rate, meaning anything corresponding to complete noise is not considered.
> Update `NoiseAwarePlacement::cost_placement` to cost errors appropriately

- README.md
The README had some out of date info on pytket extensions.
In particular it still said all of the extensions are in a single repo This is no longer true as each extension lives in its own repo.
> Fix outdated extensions info in README

- pytket/binders/circuit/main.cpp
- pytket/docs/changelog.rst
- pytket/tests/circuit_test.py
> Feature/pybind is_clifford

- pytket/binders/passes.cpp
- pytket/conanfile.py
- pytket/docs/changelog.rst
- schemas/compiler_pass_v1.json
- tket/conanfile.py
- tket/include/tket/Predicates/PassGenerators.hpp
- tket/include/tket/Transformations/BasicOptimisation.hpp
- tket/include/tket/Transformations/SingleQubitSquash.hpp
- tket/src/Predicates/PassGenerators.cpp
- tket/src/Transformations/SingleQubitSquash.cpp
- tket/src/Transformations/StandardSquash.cpp
- tket/test/src/Circuit/test_Symbolic.cpp
- tket/test/src/test_CompilerPass.cpp
> Avoid blow-up of complexity when squashing symbolic circuits

- pytket/docs/changelog.rst
- pytket/pytket/backends/backendresult.py
- pytket/tests/backend_test.py
> Allow empty `BackendResult`

- pytket/binders/pauli.cpp
- pytket/binders/tableau.cpp
- pytket/docs/changelog.rst
- pytket/tests/tableau_test.py
closes #983 
Add `QubitPauliTensor` and appropriate methods to the binders. Add a test for the methods of `UnitaryTableau` that use `QubitPauliTensor`. It should automatically be added to the docs since pauli.rst is set to automodule. Most of the docstrings are minimally adapted from the equivalent methods for `QubitPauliString`, let me know if they should be updated at all.
> Expose QubitPauliTensor for docs and tableau methods

- pytket/conanfile.py
- pytket/docs/changelog.rst
- pytket/tests/circuit_test.py
- tket/conanfile.py
- tket/include/tket/Circuit/Boxes.hpp
- tket/include/tket/Circuit/ConjugationBox.hpp
- tket/include/tket/Circuit/DiagonalBox.hpp
- tket/include/tket/Circuit/StatePreparation.hpp
- tket/include/tket/Circuit/ToffoliBox.hpp
- tket/include/tket/Ops/ClassicalOps.hpp
- tket/src/Converters/UnitaryTableauBox.cpp
- tket/src/Ops/ClassicalOps.cpp
- tket/src/Ops/FlowOp.cpp
- tket/src/Ops/MetaOp.cpp
These were just returning a null `Op_ptr`.
Fixes #999 .
> Fix implementations of symbol_substitution() for boxes that cannot contain symbols.

- .github/workflows/build_and_test.yml
- .github/workflows/coverage.yml
- .github/workflows/test_libs.yml
- libs/README.md
- tket/README.md
I learned that in conan 2, `conan build` automatically does `conan install` first. Therefore we can delete these `conan install` commands (as long as we add `--build=missing` where needed to the subsequent `conan build` commands).
> Remove unneeded `conan install` commands.

- .github/workflows/build_and_test.yml
This reverts commit 2aec89c027c0e0e402eb88887ba0bec9e6457969.
Bug was fixed in conan 2.0.11: https://github.com/conan-io/conan/pull/14712 .
> Revert "[infra] Pin conan to 2.0.9 for the `build_test_tket_windows` job. (#990)"

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/include/tket/Transformations/BasicOptimisation.hpp
- tket/src/Predicates/PassLibrary.cpp
- tket/src/Transformations/RzPhasedXSquash.cpp
- tket/test/src/test_Synthesis.cpp
> Make `SquashRzPhasedX` always squash symbols.

- pytket/docs/backends.rst
- pytket/docs/index.rst
- pytket/docs/passes.rst
- pytket/package.md
Now that the jupyterbook build is more stable I think it makes sense to link to this from the docs.
The new URL is
https://tket.quantinuum.com/examples
The build is tested on the pytket repo but the pages are deployed from the tket-site repositroy as part of the website prototype.
> link to the notebook examples built with jupyterbook

- .github/workflows/build_and_test.yml
- .github/workflows/build_libs.yml
- .github/workflows/packages.yml
- .github/workflows/release.yml
- .github/workflows/test_libs.yml
- .github/workflows/test_libs_all.yml
- conan-profiles/macos-13-xlarge
- pytket/conanfile.py
- tket/conanfile.py
Still using the self-hosted arm64 mac for Linux/arm64 builds (using docker), as I haven't yet managed to get docker running on the github-hosted VMs. (Will keep trying.)
One minor annoyance is that `actions/setup-python` can't install Python 3.9 on the arm64 Mac VMs ( https://github.com/actions/setup-python/issues/696 ), so I use brew to install Python 3.9 instead.
Release workflow tested here: https://github.com/CQCL/tket/actions/runs/6404838599 .
(I'll need to modify the names of the "required" checks after this merge: three showing as "required" don't exist anymore.)
> Use github-hosted runners for MacOS arm64 builds

- pytket/docs/changelog.rst
- pytket/pytket/qasm/qasm.py
- pytket/tests/qasm_test.py
Also improve the docstrings a bit.
Closes #1019 .
> Make maximum classical register width a parameter of QASM converters

- pytket/docs/conf.py
- pytket/docs/requirements.txt
This fixes a API docs build issue which is caused by the new `pydata-sphinx-theme` [0.14.2 release](https://github.com/pydata/pydata-sphinx-theme/releases/tag/v0.14.2). The pydata-sphinx-theme is the parent theme of the sphinx book theme which we use for the docs.
This release introduced a new warning which caused the docs build to fail. The warning is the following...
________________________________________
#69 39.94 WARNING: The default value for `navigation_with_keys` will change to `False` in the next release. If you wish to preserve the old behavior for your site, set `navigation_with_keys=True` in the `html_theme_options` dict in your `conf.py` file.Be aware that `navigation_with_keys = True` has negative accessibility implications:https://github.com/pydata/pydata-sphinx-theme/issue …
> Remove docs build warning from `pydata-sphinx-theme` 0.14.2 and upgrade sphinx version

- pytket/docs/getting_started.rst
The qiskit documentation mentions `ibmq_belem`. That system has now been retired by IBMQ,The following systems have been retired on September 26th: ibmq_lima, ibmq_belem, ibmq_quito, ibmq_manila, and ibmq_jakarta.
So replaced it with the `ibm_nairobi`  in the documentation.
> Updated Qiskit Documentation

- .github/workflows/build-with-nix.yml
- README.md
- pytket/CMakeLists.txt
This is because the original version (v20) was not compatible with System Identity Protection on Macos
> Bumped install-nix-action to v23

- libs/tkassert/CMakeLists.txt
- libs/tkassert/conanfile.py
- libs/tkassert/test/conanfile.py
> [tkassert] Link tklog as public

- pytket/stub_generation/regenerate_stubs
For some reason `pkgutil` is including these libraries in its modules list (with latest version on Linux).
Also apply black formatting (first commit here).
> Skip non-module libraries when generating stubs.

- .github/workflows/build_and_test.yml
Fixes #1115, also see comments there
Added a job to build and test workflow whose only job is to check that all other jobs did not explicitly fail or were not canceled (skipped jobs are ok). How this fixes the problem:
- After merging, only use the new job as a required check in the github settings -> No longer need to define a required check for the individual jobs
- No longer have to worry about naming issues that occur with matrix strategy jobs
After merging: In a follow-up PR, should be able to remove the dummy job `build_test_tket_not_required` since it should no longer be required
> add job to check all build and test jobs successful

- .github/workflows/build_and_test.yml
Removed no longer necessary job `build_test_tket_not_required`
- Shouldn't forget to change the required checks for the build and test workflow to only include the "All jobs succeeded" job. (I don't have the permissions to do this)
> remove tket build dummy job

- .github/workflows/release.yml
- conan-profiles/macos-11
- pytket/docs/changelog.rst
Release workflow tested [here](https://github.com/CQCL/tket/actions/runs/6891015932).
> Drop support for MacOS 11

- .gitignore
- nix-support/pytket.nix
- pytket/setup.py
The previous nix derivations for pytket did not include the .pyi files for the _tket directory. This meant that mypy checks could not establish the type information for the binders. With this PR, those files are included and mypy runs successfully. I have thus added mypy checks to the checkPhase of pytket.
This issue was discovered when running mypy checks on a local pytket-qir clone I'm working on adding nix support to.
I have also .gitignored the 'result' directory, in case someone runs `nix build .#[package]` from within the source directory.
> Add mypy support to nix builds of pytket

- pytket/docs/extensions.rst
- pytket/docs/index.rst
1. Removing pytket-ionq extension form the list of supported Backends. As far as I know its no longer working.
2. Mentioning the new qulacs density matrix simulator in extensions index.
3. Updated the sidebar links to the other documentation pages to be consistent with what we have in the extensions API docs and manual pages.
> Remove `pytket-ionq` backend from index and add sidebar links

- pytket/docs/extensions.rst
I've now built the docs for pytket-qujax on the tket website. I'm updating the link from the index page to point to 
https://tket.quantinuum.com/extensions/pytket-qujax/
The only extensions that are on the index page that do not point to https://tket.quantinuum.com are `pytket-aqt` and `pytket-qsharp`.
There are known issues with pytket-aqt and the source repository has a different file structure which we would have to deal with on the tket-site.
For pytket-qsharp I'm having trouble installing the dotnet SDK in the website but can keep trying if we want to update that link as well.
> Update pytket-qujax link in the documentation

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/include/tket/Characterisation/Cycles.hpp
- tket/src/Characterisation/Cycles.cpp
- tket/src/Characterisation/FrameRandomisation.cpp
- tket/test/CMakeLists.txt
- tket/test/src/test_FrameRandomisation.cpp
Fixes https://github.com/CQCL/tket/issues/1015.
FrameRandomisations works by first finding a set of subcircuits (or "cycles") of the given set of OpType and then wiring an OpType::noop vertex in the in and out edges of each of these cycles. To add the "frames" for randomisation, these OpType::noop vertices have their type changed.
"Cycles" are found in causal order and "noop frames" are added in causal order. 
The first fix is for finding cycles. The cycle finding works by iterating through the circuit slice-by-slice, adding vertices to cycles if they have the permitted `OpType`. However, the original code had an incorrect assumption that all `Edge` held in a `Slice` object were connected to vertices held in the slice. This is not true and could lead to incorrect cycle objects. This is …
> Fix Cycle handling in FrameRandomisation

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/src/Placement/NoiseAwarePlacement.cpp
- tket/test/src/Placement/test_NoiseAwarePlacement.cpp
https://github.com/CQCL/tket/issues/922 brings up that qubits without 2-qubit gates aren't placed by `NoiseAwarePlacement`. This is fine for `GraphPlacement` as these qubits will be dynamically assigned during routing, with their allocation unrelated to performance as it assumes "no noise", but for `NoiseAwarePlacement` they could still be assigned to `Node` in the `Architecture` that have smaller error rates.
However, the expectation is that typical circuits won't have qubits without any 2-qubit gates, i.e. this is a special case fix. My proposed solution is:
• If the Circuit has qubits with 2-qubit gates and qubits without 2-qubit gates, don't assign the qubits without 2-qubit gates to any `Node`, as these `Node` may be better used as dynamically assigned later.
• If the Circuit …
> Update Noise Aware Placement for Circuits with only single qubit gates

- pytket/pytket/zx/tensor_eval.py
There was an issue with the `tensor_from_mixed_diagram` function in the `pytket.zx` module. This was due to a new release of the quimb package version 1.7.0.
The 1.7.0 release dropped the `opt_einsum` dependency casuing the error. It seems there is now equivalent functionality in the `cotengra` package under the name of `greedy` instead of `random-greedy`.
See the build failure in https://github.com/CQCL/pytket/issues/279
> Fix `pytket.zx` dependency issue

- pytket/binders/circuit/Circuit/main.cpp
- pytket/docs/changelog.rst
- pytket/tests/circuit_test.py
Fix invalid registers returned by q_registers and c_registers
Any set of UnitIds with the same name but not consecutive indices will not be returned as a UnitRegister
Fixes #1160
> Fix invalid registers returned by q_registers and c_registers

- pytket/binders/circuit/Circuit/add_op.cpp
- pytket/conanfile.py
- pytket/pytket/_tket/circuit.pyi
- pytket/tests/add_circuit_test.py
- tket/conanfile.py
Commonly used enough that having to switch to add_gate confuses people.
> [feature] add a Circuit method for Reset

- .github/workflows/build_and_test.yml
- pytket/conanfile.py
- tket/conanfile.py
We were using a hack to get the ccache path, which stopped working because with version 4.9.0 the path for some reason only contained "4.9". Use a different hack which works (for now).
Fixes #1191 .
> Fix determination of ccache path on Windows

- build-without-conan.md
- pytket/setup.py
I sometimes find that building TKET (using cmake) consumes too much memory. One workaround is to restrict the number of threads. This can be done with the `-j` parameter to `cmake`. But the binders are built from within a python script. This PR allows one to set an environment variable that's picked up by that script.
> Allow restriction of number of threads when building pytket using cmake.

- .github/workflows/build_libs.yml
- .github/workflows/packages.yml
- .github/workflows/release.yml
- conan-profiles/linux-armv8-gcc10-libstdc++
- conan-profiles/linux-armv8-gcc12
- conan-profiles/linux-x86_64-gcc10-libstdc++
- conan-profiles/linux-x86_64-gcc12
- pytket/conanfile.py
- tket/conanfile.py
- tket/src/Circuit/Boxes.cpp
- tket/src/Predicates/CompilationUnit.cpp
See https://peps.python.org/pep-0600/ . Doing this now as it seems necessary for Python 3.12 support.
By default the newer manylinux platforms use gcc 12 and libstdc++11, so update the conan profiles to match that configuration. Fix a couple of build warnings arising from this.
> Use PEP 600 manylinux containers to build pytket

- .github/workflows/build-without-conan.yml
- build-without-conan.md
- libs/tkassert/test/conanfile.py
- libs/tklog/test/conanfile.py
- libs/tkrng/test/conanfile.py
- libs/tktokenswap/test/conanfile.py
- libs/tkwsm/test/conanfile.py
- pytket/conanfile.py
- tket/conanfile.py
Update to latest conan-packaged versions of catch2 and repidcheck.
> Update versions of catch2 and rapidcheck.

- .github/workflows/build_and_test.yml
- .github/workflows/compare-pytket-coverage
Only do the pytket coverage check for PRs to `develop`. Since we are comparing with the results of the latest push to `develop`, this is not meaningful for PRs to other branches (e.g. `main`, which may be behind `develop`).
Also add a tolerance for random variation.
> Only check pytket coverage for PRs to develop.

- .github/workflows/build_and_test.yml
Don't install pytket with the "ZX" option on Python 3.12 (which is used on the weekly scheduled runs).
Relates to #1200 .
> Don't try to install ZX module with Python 3.12.

- .github/workflows/packages.yml
- .github/workflows/release.yml
Now that we have access to the buildjet runners in he tket repo, we can use them to build Linux/ARM use.
> Use ARM-Linux runners from buildjet instead of using docker on the self-hosted Mac

- libs/tktokenswap/conanfile.py
- libs/tktokenswap/test/conanfile.py
- libs/tkwsm/conanfile.py
- libs/tkwsm/test/conanfile.py
Update tkwsm and tktokenswap to use boost 1.84.0 (follow-up PR will do the same for tket and update its lib dependencies).
> Use boost 1.84.0 in libs.

- pytket/docs/changelog.rst
- pytket/pytket/wasm/wasm.py
- pytket/tests/classical_test.py
This provides a stable way to retrieve the WASM bytecode (previously only possible with the `_wasm_file` attribute).
Useful for https://github.com/CQCL/pytket-quantinuum/issues/344 .
> Add method to get bytecode from a `WasmFileHandler`

- .github/workflows/build_and_test.yml
This reverts commit c257befc4afddda515eef55a46a0b96994b1038f now that numba is available for python 3.12.
There is still an [issue](https://github.com/CQCL/tket/issues/1242) on Ubuntu, so keep skipping ZX for that platform on the python 3.12 run.
Also remove references in the workflow to `matrix.python-version` which doesn't exist (and apparently resolves to the empty string).
Tested [here](https://github.com/CQCL/tket/actions/runs/7755286684/job/21150352628).
Closes #1200 .
> Revert "Don't try to install ZX module with Python 3.12. (#1203)"

- .github/workflows/build_and_test.yml
- .github/workflows/release.yml
- pytket/conanfile.py
- tket/conanfile.py
CI builds on Windows started failing, probably because of [this](https://github.com/actions/runner-images/issues/9115) change to Powershell version. This fixes the issue.
Fixes #1246 .
> Fix build command on Windows

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/src/PauliGraph/PauliGraph.cpp
- tket/test/src/test_CompilerPass.cpp
Fixes a bug in applying `PhasedX` gates as sequences of `Rz` and `Rx` gates.
Fixes #1244 .
> Don't reuse "stale" Pauli stabilizers when generating Pauli graphs

- pytket/binders/circuit/boxes.cpp
- pytket/binders/circuit/main.cpp
- pytket/pytket/_tket/circuit.pyi
Previous docstrings for PauliExpPairBox did not clarify the lack of commutation requirements. Reworked it to address this and provide some explanation as to why a user might use the box.
> Change docstrings for PauliExpPairBox

- pytket/docs/circuit.rst
Adding the `PauliExpCommutingSetBox` to the `pytket.circuit` docs. This was added in [pytket 1.17](https://tket.quantinuum.com/api-docs/changelog.html#id9) but was left out of the API docs.
Hopefully we can catch these sorts  API docs omissions using the [sphinx.ext.coverage extension](https://www.sphinx-doc.org/en/master/usage/extensions/coverage.html).
closes #1261
> Add `PauliExpCommutingSetBox` to API docs

- pytket/conanfile.py
- pytket/docs/extensions.rst
- pytket/docs/faqs.rst
- pytket/docs/getting_started.rst
- pytket/docs/index.rst
- pytket/docs/passes.rst
- pytket/package.md
- pytket/setup.py
- tket/conanfile.py
- tket/include/tket/Gate/GateUnitaryMatrixImplementations.hpp
Fixed some invalid links on the extensions index page
https://tket.quantinuum.com/api-docs/extensions.html
Also did a search for old cqcl.github.io links and removed those.
The only remianing cqcl.github.io links point to the pytket-qsharp and pytket-aqt docs which are not build on the tket website yet.
Closes #1257 in https://github.com/CQCL/tket/pull/1258/commits/2fcce701cf67e1b9da529e0fc0b6b2d4ac4b85d1
> Fix invalid links on pytket extensions index docs page and elsewhere

- pytket/conanfile.py
- pytket/docs/circuit.rst
- pytket/docs/extensions.rst
- pytket/docs/faqs.rst
- pytket/docs/getting_started.rst
- pytket/docs/index.rst
- pytket/docs/passes.rst
- pytket/package.md
- pytket/setup.py
- tket/conanfile.py
- tket/include/tket/Gate/GateUnitaryMatrixImplementations.hpp
Cherry-picking the fixes from #1258 and #1261 onto `docmain` so we don't have to wait for the next release for the fixes to be in the API docs.
> Cherry-pick doc fixes onto `docmain`

- pytket/CMakeLists.txt
- pytket/binders/circuit/Circuit/add_op.cpp
- pytket/binders/circuit/Circuit/main.cpp
- pytket/binders/include/circuit_registers.hpp
- pytket/conanfile.py
- pytket/docs/changelog.rst
- pytket/pytket/_tket/circuit.pyi
- pytket/tests/circuit_test.py
- tket/conanfile.py
- tket/include/tket/Circuit/Boxes.hpp
- tket/src/Circuit/Boxes.cpp
- tket/src/Circuit/macro_manipulation.cpp
- tket/test/src/Circuit/test_Boxes.cpp
- tket/test/src/Circuit/test_Circ.cpp
Drop the restriction that a `CircBox` must have default registers. Add a couple of methods for adding a `CircBox` by matching up registers instead of individual qubits.
Closes #1057 .
Closes #1059 .
> Methods for adding a `CircBox` registerwise

- .github/workflows/build_and_test.yml
- CONTRIBUTING.md
- libs/tklog/src/TketLog.cpp
- pytket/conanfile.py
- tket/conanfile.py
- tket/src/Architecture/DistancesFromArchitecture.cpp
- tket/src/Clifford/UnitaryTableau.cpp
- tket/src/Predicates/Predicates.cpp
v17 is no longer available from homebrew and the default has been changed to 18; therefore use v18 and format code accordingly.
> Update to clang-format 18

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/src/Clifford/SymplecticTableau.cpp
- tket/test/src/test_UnitaryTableau.cpp
Add conversions for `SX`, `SXdg`, `ZZMax`, `ECR` and `ISWAPMax`.
Fixes #1268 .
> Add missing op types to method for converting circuit to unitary tableau

- pytket/binders/passes.cpp
- pytket/conanfile.py
- pytket/docs/changelog.rst
- pytket/pytket/_tket/passes.pyi
- pytket/tests/predicates_test.py
- tket/CMakeLists.txt
- tket/conanfile.py
- tket/include/tket/Circuit/Circuit.hpp
- tket/include/tket/Circuit/DAGDefs.hpp
- tket/include/tket/Predicates/PassGenerators.hpp
- tket/include/tket/Transformations/CliffordResynthesis.hpp
- tket/proptest/src/proptest.cpp
- tket/src/Circuit/Boxes.cpp
- tket/src/Circuit/Circuit.cpp
- tket/src/Circuit/SubcircuitFinder.cpp
- tket/src/Circuit/macro_circ_info.cpp
- tket/src/Circuit/macro_manipulation.cpp
- tket/src/Ops/MetaOp.cpp
- tket/src/Predicates/PassGenerators.cpp
- tket/src/Predicates/Predicates.cpp
- tket/src/Transformations/CliffordResynthesis.cpp
- tket/test/CMakeLists.txt
- tket/test/src/Circuit/test_Circ.cpp
- tket/test/src/Passes/test_CliffordResynthesis.cpp
- Add a method to partition the vertices of a circuit having a given property into large connected convex subsets.
- Using this method with the "Clifford" property, add a new Clifford resynthesis pass, which can either apply a default resynthesis method or one provided by the user. The default method essentially converts to a unitary tableau and back and then applies the existing `clifford_simp()` transform.
Closes #1266 .
Relates to #1267 .
> Subcircuit finding and Clifford resynthesis

- pytket/docs/changelog.rst
- pytket/pytket/backends/backendresult.py
- pytket/pytket/utils/distribution.py
- pytket/tests/distribution_test.py
Add an optional `min_p` argument to `BackendResult.get_probability_distribution()` and to the constructor of a `ProbabilityDistribution`.
Closes #1253 .
> Make probability threshold configurable, defaulting to zero

- pytket/conanfile.py
- pytket/tests/circuit_test.py
- tket/conanfile.py
- tket/src/Circuit/CommandJson.cpp
We were just constructing these exceptions without throwing them. This led to a segfault.
Fixes #1243 .
> Throw exceptions.

- pytket/conanfile.py
- tket/conanfile.py
- tket/include/tket/Circuit/Circuit.hpp
- tket/src/Circuit/SubcircuitFinder.cpp
- tket/test/src/Passes/test_CliffordResynthesis.cpp
The failures were due to the fact that we were implicitly identifying the vertices of the graph constructed by `boost::transitive_closure()` with the vertices of the original graph. I tried to fix this by providing an associative map; but for some reason the resulting generated graph was always the complete graph on all vertices. In the end I implemented transitive closure myself, which we can do fairly efficiently for DAGs if we start with a topological sort.
Fixes #1279 .
> Fix subcircuit finding algorithm

- pytket/tests/wasm-generation/wasmfromrust/src/lib-2.rs
- pytket/tests/wasm-generation/wasmfromrust/src/lib.rs
The files where the wasm is compiled from via rust had gone missing. I have added them back in.
When adding them back in, I was hit by:
```git add wasmfromrust/src/
The following paths are ignored by one of your .gitignore files:
pytket/tests/wasm-generation/wasmfromrust/src
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
```
But I have not found any ignores that would explain this. Any ideas?
> add wasm files that had gone missing

- pytket/conanfile.py
- pytket/pytket/circuit/logic_exp.py
- pytket/tests/circuit_test.py
- tket/conanfile.py
- tket/src/Circuit/Boxes.cpp
Also add an early check to the `CircBox` constructor that the circuit is boxable.
Fixes #1289 .
> Make trivial renames on registerwise classical operations possible

- pytket/conanfile.py
- tket/conanfile.py
- tket/include/tket/Circuit/DAGDefs.hpp
- tket/src/Circuit/Circuit.cpp
- tket/src/Circuit/SubcircuitFinder.cpp
- tket/test/src/Passes/test_CliffordResynthesis.cpp
This PR contains two fixes and three small refactors:
- fix 1: Fix an obvious typo.
- fix 2: Use own version of set-difference method. I do not understand why, but on the MacOS arm64 platform, `std::set_difference` was giving incorrect results!
- refactor 1: Use `std::size_t` everywhere for vertex indexing, for consistency.
- refactor 2: Index vertices earlier when finding subcircuits.
- refactor 3: Simplify the computation of successors and predecessors of convex unions.
Of the refactors, 1 and 2 were early attempts to fix the bug; they seem worth retaining.
Fixes #1291 .
> Fix problems with subcircuit finding

- pytket/docs/changelog.rst
- pytket/pytket/qasm/qasm.py
- pytket/tests/qasm_test.py
Add special logic to detect (and raise an error for) empty custom gates, to match previous behaviour.
Fixes #1299 .
> Decompose boxes before converting to QASM

- tket/README.md
The instructions for building and testing `tket` in the README were incorrect.
> doc: Fix incorrect build/test instructions in the README

- pytket/binders/unitid.cpp
- pytket/conanfile.py
- tket/conanfile.py
- tket/test/src/Graphs/test_ArticulationPoints.cpp
- tket/test/src/test_Architectures.cpp
- tket/test/src/test_CompilerPass.cpp
- tket/test/src/test_LexiRoute.cpp
- tket/test/src/test_MappingVerification.cpp
- tket/test/src/test_Predicates.cpp
- tket/test/src/test_RoutingPasses.cpp
- tket/test/src/test_json.cpp
Adds explicit parameter types when constructing `Architecture`s on the tests.
In my machine, compilation was failing due to dissambiguation errors:
```bash
../../test/src/Graphs/test_ArticulationPoints.cpp:148:44: error: call of overloaded ‘Architecture(<brace-enclosed initializer list>)’ is ambiguous
148 |   Architecture arc({{0, 1}, {1, 2}, {2, 3}});
|                                            ^
In file included from ../../test/src/Graphs/test_ArticulationPoints.cpp:21:
../../include/tket/Architecture/Architecture.hpp:92:12: note: candidate: ‘tket::Architecture::Architecture(const std::vector<std::pair<unsigned int, unsigned int> >&)’
92 |   explicit Architecture(const std::vector<std::pair<unsigned, unsigned>> &edges)
|            ^~~~~~~~~~~~ …
```
> fix: Explicit types in Architecture initializers

- pytket/docs/changelog.rst
- pytket/pytket/qasm/qasm.py
- pytket/tests/qasm_test.py
Instead of putting the gate definition immediately before the operation and after the "if", which is invalid, move all gate definitions to the top of the file (just below the header and include statements).
This necessitated some refactoring of the code: see commits.
Fixes #1301 .
> Correct position of custom gate definitions needed for conditional operations

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/src/Transformations/MeasurePass.cpp
- tket/test/src/test_CompilerPass.cpp
When `allow_partial` is `false` we were allowing measurements to commute past succeeding gates even when their target bit was later written to by another measurement. This is invalid and also invalidates the DAG.
Fixes #1305 .
> Fix `DelayMeasures()` pass when two measurements target the same bit

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/include/tket/Circuit/Circuit.hpp
- tket/test/src/Circuit/test_Circ.cpp
Check for invalid arguments before adding a vertex to (thus potentially invalidating) the circuit.
Fixes #979 .
> Don't add a vertex to the circuit when an operation is added with invalid arguments

- pytket/conanfile.py
- tket/conanfile.py
- tket/src/Clifford/ChoiMixTableau.cpp
- tket/test/src/test_ChoiMixTableau.cpp
I spotted a v minor error in how the ChoiMixTableau constructor from rows handled the internal transposing of the input segment. This can lead to phase errors in constructed tableaux. This constructor is currently not used internally or externally available so this is not a user facing bug, just bad code (my bad).
N/A
> Correct phase handling on ChoiMixTableau constructor

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/src/Transformations/RedundancyRemoval.cpp
- tket/test/src/test_CompilerPass.cpp
Fixes a "bug" in `RemoveRedundancies` that caused it to ignore `Phase` gates.
Closes #1316 .
> Let `RemoveRedundancies` remove `Phase` gates

- pytket/docs/changelog.rst
- pytket/setup.py
The quimb 1.8.0 release fixes the issue with scipy 1.13 so we don't need to pin to scipy 1.12 anymore.
> Relax scipy constraint and require latest quimb

- pytket/docs/requirements.txt
Doing a cherry pick of the theme version bump in #1334 to the `docmain` branch. 
This means we can get the upgraded theme into the website build without waiting for a new release of pytket
> Cherry-pick docs theme upgrade to `docmain`

- pytket/conanfile.py
- tket/conanfile.py
- tket/include/tket/Transformations/PhasedXFrontier.hpp
- tket/src/Transformations/PhasedXFrontier.cpp
- tket/test/src/test_PhasedXFrontier.cpp
Closes #1306
This solves the issue by treating any classically controlled gate as a barrier when squashing and turning gates to global gates. This is the only simple solution I could think of, as squashing classically controlled operation is always a bit tricky and comes with many edge cases.
> fix: Handle classical control in PhasedXFrontier

- .github/workflows/release.yml
Ensure we use a version of `delocate` that does not rename the wheel.
I have checked that the wheels produced do have `macosx_12_0_arm64` in their name.
We should also investigate whether there really is a compatibility issue here, as `delocate` 0.11 would seem to indicate. I'll raise a new issue for that (and if possible reverting this change).
Fixes #1341 .
> Use delocate 0.10.x when building pytket wheels on `macos-13-xlarge`

- pytket/docs/changelog.rst
- pytket/pytket/wasm/wasm.py
- pytket/tests/classical_test.py
Reject wasm functions with multiple return values
> remove support for multi return wasm functions

- pytket/docs/circuit_class.rst
Doing a cherry-pick to update with the changes in #1352 so we don't have to wait for the next pytket release for the updated docs.
> Update `docmain` with missing `Circuit` methods

- pytket/docs/changelog.rst
- pytket/pytket/backends/status.py
Add "CANCELLING" and "RETRYING" statuses to `pytket.backends.status.StatusEnum`
n/a
> Add "CANCELLING" and "RETRYING" statuses

- .github/workflows/pytket_benchmarking.yml
Adds a workflow to run benchmarks on each new PR. The version of pytket built from the PR is used in the benchmarks. At the moment this is a simple comparison to Qiskit on quantum volume circuits.
I would like to have a wider conversation about the compilers to compare agains, and the circuits to compile. The outcome of those conversation would feature in later PRs.
I also note that the benchmarks are quite slow. I will experiment with parallelisation in future PRs.
N/A
> ci: Add automated benchmarking workflow

- .github/workflows/build-with-nix.yml
Previously this was run only once per week due to the time taken to build via Nix (most dependencies had to be compiled, then tket, etc).
However, with Cachix, build times have decreased dramatically, and I propose we keep the cache hot so that running on the latest commit remains fast.
> Set Nix workflow to run on PRs and commits (not just weekly)

- .github/workflows/build-with-nix.yml
- .github/workflows/build_and_test.yml
- .github/workflows/build_libs.yml
- .github/workflows/coverage.yml
- .github/workflows/docs.yml
- .github/workflows/pytket_benchmarking.yml
- .github/workflows/test_libs.yml
- .github/workflows/valgrind.yml
- CONTRIBUTING.md
- pytket/docs/backends.rst
Update CI workflows to run on push and PR to `main` instead of `develop`.
Once approved, I would:
- change the branch protection rules on the repo (note that some of the "Required" checks below will not run on this PR);
- merge this into `develop`;
- make `main` the default branch;
- make a PR from `develop` into `main`;
- merge that.
We will also need to update the workflows on `tket-site`, so that they only publish released versions (which will be identifiable by tag).
> Switch workflows to target `main` only

- .github/workflows/build_and_test.yml
- libs/tklog/src/TketLog.cpp
- pytket/conanfile.py
- tket/conanfile.py
- tket/src/Architecture/DistancesFromArchitecture.cpp
- tket/src/Clifford/UnitaryTableau.cpp
- tket/src/Predicates/Predicates.cpp
Previously the formatting check would fail without indicating exactly what was wrong. This PR makes it print a diff which the developer can then apply to their branch to fix the issues.
This became necessary since clang-format began changing its rules on updates to minor versions that are not easily available on all platforms.
Also actually fix the latest formatting errors.
> Show diff from clang-format.

- nix-support/pytket.nix
- nix-support/third-party-python-packages.nix
- pytket/docs/changelog.rst
- pytket/pytket/qasm/qasm.py
- pytket/pytket/quipper/quipper.py
- pytket/setup.py
Needs a couple of small tweaks to the qasm and quipper parsers.
Closes #1356 .
> Use `lark` package instead of deprecated `lark-parser`

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/src/Circuit/latex_drawing.cpp
- tket/test/src/Circuit/test_Circ.cpp
Note that this is the only character we need to worry about, since `UnitID` names are restricted to `"[a-z][A-Za-z0-9_]*"`.
Fixes #1363 .
> Escape underscores when converting to latex

- .github/workflows/build-without-conan.yml
- .github/workflows/build_and_test.yml
- .github/workflows/linuxbuildwheel
- .github/workflows/pytket_benchmarking.yml
- .github/workflows/release.yml
- build-without-conan.md
- nix-support/third-party-python-packages.nix
- pytket/CMakeLists.txt
- pytket/README.md
- pytket/conanfile.py
- recipes/pybind11_json/all/conandata.yml
- recipes/pybind11_json/config.yml
- tket/conanfile.py
> Update to pybind11_json 0.2.14

- pytket/docs/changelog.rst
- pytket/pytket/circuit/logic_exp.py
- pytket/tests/classical_test.py
- pytket/tests/qasm_test.py
> Allow constant `BitLogicExp` as condition

- .github/workflows/release.yml
I don't know if this was why https://github.com/CQCL/tket/actions/runs/9109560293/workflow skipped the `publish_to_pypi` step; it seems possible, but as far as I can see this inconsistency has been there for a while, so I'm not sure.
> Fix name for consistency and to match reference in `publish_to_pypi`.

- pytket/conanfile.py
- pytket/docs/changelog.rst
- pytket/tests/circuit_test.py
- tket/conanfile.py
- tket/src/Circuit/macro_manipulation.cpp
- tket/test/src/Circuit/test_Circ.cpp
resolves https://github.com/CQCL/tket/issues/877
> Allow barriers when dagger or transpose circuits

- .github/workflows/valgrind.yml
For some reason the valgrind CI runs have started to [fail](https://github.com/CQCL/tket/actions/runs/9343595071/job/25721020802) on the `ubuntu-24.04` runners during valgrind installation, the run being abruptly cancelled.
Revert to using `ubuntu-22.04` until this issue is resolved.
Fixes #1433 .
> Revert to using ubuntu-22.04 runner for valgrind checks.

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/src/Transformations/Decomposition.cpp
- tket/test/src/Passes/test_CliffordResynthesis.cpp
Add special-case handling of `NPhasedX` so that gates recognized as Clifford actually get decomposed.
Fixes #1408 .
> Handle `NPhasedX` gates in `decompose_cliffords_std()`

- pytket/binders/circuit/Circuit/main.cpp
- pytket/conanfile.py
- pytket/docs/changelog.rst
- pytket/pytket/_tket/circuit.pyi
- tket/conanfile.py
- tket/include/tket/Circuit/Circuit.hpp
- tket/src/Circuit/basic_circ_manip.cpp
- tket/src/Predicates/PassGenerators.cpp
- tket/test/src/Circuit/test_Circ.cpp
Solves https://github.com/CQCL/tket/issues/1434
> update remove blank wires to keep classical bits

- .github/workflows/build_and_test.yml
Tested here: https://github.com/CQCL/tket/actions/runs/9396857013/job/25878869049
There was an issue with the ZX test running on Ubuntu with Python 3.12 but this seems to be working now.
Closes #1242 .
> Run ZX test with all Python versions

- pytket/conanfile.py
- pytket/tests/predicates_test.py
- tket/conanfile.py
- tket/src/Predicates/PassGenerators.cpp
Found the problem from yesterday: after updating the parameter I forgot to change the value in the pass. Should work now.
( see  https://github.com/CQCL/tket/pull/1435 )
> Fix FlattenRelabelRegistersPass

- pytket/conanfile.py
- pytket/docs/changelog.rst
- pytket/tests/predicates_test.py
- tket/conanfile.py
- tket/src/Predicates/PassGenerators.cpp
The change in #1441 causes test failures in dependent packages; revert for now.
I've checked that the pytket-quantinuum tests all pass with a wheel built from this branch.
> Revert to removing blank classical wires in `FlattenRelabelRegistersPass`

- pytket/mypy.ini
- pytket/pytket/qasm/qasm.py
- pytket/pytket/utils/operators.py
- pytket/pytket/utils/symbolic.py
- pytket/pytket/zx/tensor_eval.py
- pytket/tests/circuit_test.py
- pytket/tests/predicates_test.py
- pytket/tests/qubitpaulioperator_test.py
- pytket/tests/transform_test.py
- pytket/tests/utils_test.py
- pytket/tests/zx_diagram_test.py
Fixes #1486 .
Also a bunch of mypy fixes.
The nix failure is expected because it's using the older sympy which has different mypy requirements. (Will make a separate issue for that.)
> Use float not int for QPO coefficient.

- flake.lock
- flake.nix
- nix-support/pytket.nix
- nix-support/third-party-python-packages.nix
I updated nixpkgs to get everything else up to date too, but sympy 1.13 is too new to have found its way into nixpkgs yet, so I added a custom derivation for it based on the existing one in nixpkgs.
Resolves #1488
> Update flake inputs, use custom sympy 1.13 derivation

- pytket/docs/extensions.rst
Changing the link for the docs of pytket-cutensornet to the old version of the docs (which is still maintained for pytket-cutensornet) since there are some problems with the new docs (see issue linked below).
NOTE: This is a temporary solution.
https://github.com/CQCL/pytket-cutensornet/issues/139
> Changed the link to old pytket-cutensornet docs

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/src/Circuit/Multiplexor.cpp
- tket/test/src/Circuit/test_Multiplexor.cpp
https://github.com/CQCL/tket/issues/1459
> Prevent MultiplexedTensoredU2Box passing empty argument to MultiplexedRotationBox

- pytket/pytket/utils/results.py
Closes #868 .
I don't see a good reason for the restriction, and extensions sometimes want to pass other types such as dictionaries.
> Allow any kwarg type.

- pytket/docs/_static/nav-config.js
- pytket/docs/conf.py
Updating the navbar config to contain the user guide after restructuring the docs in https://github.com/CQCL/pytket-docs/pull/339
Shows user guide rather than user-manual + examples
Also updated to the latest commit of the quantinuum-sphinx submodule
finally made a minor change to `conf.py` to fix some local build warnings.
If build and serve the html locally I see the updated navbar working fine.
> docs: update navbar config and theming submodule

- pytket/docs/_static/nav-config.js
- pytket/docs/conf.py
cherry-picking the commit from https://github.com/CQCL/tket/pull/1523 onto `docmain` so it will be cloned by the website.
Would be good to retire the `docmain` branch soon.
> docs: cherry-pick navbar fixes to `docmain`

- pytket/docs/_static/nav-config.js
Should enable the links to work on both `tket.quantinuum.com` and `docs.quantinuum.com/tket`
> fix: correct navbar links to work on subpath

- pytket/docs/_static/nav-config.js
Applying fix in #1527  to `docmain`.
Cancelled CI checks as they aren't needed.
> cherry-pick navbar links to `docmain`

- flake.lock
- flake.nix
- nix-support/symengine.patch
… the patch file to fit
To keep the nix build in sync, symengine needed updating. Fortunately the flake tracks nixpkgs' master branch, which has had symengine 0.12 for a week. So a `nix flake update` handled that.
Additionally, as we patch symengine to have it expose symengine libraries through INTERFACE_LINK_LIBRARIES, the patch file needed adjusting to take into account the new symengine's `cmake/SymEngineConfig.cmake.in` file.
I have run the tests on my local linux machine.
N/A
- [-] I have commented hard-to-understand parts of my code.
- [-] I have made corresponding changes to the public API documentation.
- [-] I have added tests that prove my fix is effective or that my feature works.
- [-] I have updated the changelog with any user-facing changes.
> Updated flake.lock to bring symengine-0.12.0 into nix

- pytket/conanfile.py
- pytket/docs/changelog.rst
- pytket/tests/classical_test.py
- tket/conanfile.py
- tket/include/tket/Ops/ClassicalOps.hpp
- tket/test/src/Circuit/test_Symbolic.cpp
The method, although trivial in all cases, needs to be defined on all the derived classes of `ClassicalOp`, in order to preserve the type information.
Fixes #1536 .
> Fix symbol substitution for classical operations

- pytket/docs/extensions.rst
Adding a link to https://tket.quantinuum.com/extensions/pytket-azure/
> docs: Add pytket-azure to list of extensions

- pytket/docs/extensions.rst
Cherry picking the commit from #1540 to make sure the link to the pytket-azure docs is visible
> Update `docmain` with link to pytket-azure docs

- pytket/pytket/circuit/__init__.py
- pytket/pytket/wasm/wasm.py
- pytket/tests/classical_test.py
- Add a new WasmModuleHandler class that takes raw wasm_module bytes on construction, but has the same interface as WasmFileHandler.
- WasmFileHandler now inherits from WasmModuleHandler.
- Split checking of the WASM module into a new function so it can be called after initialisation if required.
- Adds new cached properties, bytecode, bytecode_base64 and module_uid which allow lazy loading of the module in encoded form, or computation of a unique identifier for the module.
- Add deprecated properties _check_file, wasm_file_encoded and _wasmfileuid to maintain compatibility with existing versions of pytket-qir and pytket-quantinuum.
- Remove some exceptions that are no longer possible.
The primary intention behind this PR is to allow usage of WASM modules without having to access the file …
> feat: Refactor WASM module

- pytket/binders/circuit/classical.cpp
- pytket/docs/changelog.rst
- pytket/pytket/_tket/circuit.pyi
- pytket/tests/classical_test.py
Previously if you constructed a `RangePredicateOp` from Python with named arguments they were interpreted in the wrong order.
> Fix order of `lower` and `upper` in constructing `RangePredicateOp`

- libs/tktokenswap/conanfile.py
- libs/tktokenswap/test/conanfile.py
- libs/tkwsm/conanfile.py
- libs/tkwsm/test/conanfile.py
Will update tket to use this version of boost and the new library versions in a subsequent PR.
> Update libs to boost 1.86.0.

- .github/workflows/build_and_test.yml
I am not sure why this succeeded before (maybe something changed in a conan version bump?).
> Install pytket requirements before version consistency checks

- .github/workflows/valgrind.yml
- pytket/conanfile.py
- tket/conanfile.py
- tket/test/src/Placement/test_NoiseAwarePlacement.cpp
Fixes #1402 .
Using the version of valgrind installed by default on ubuntu-24.04 we have to ignore "realloc() of size 0" warnings. It's not clear where these come from, but probably eigen.
> Run valgrind on ubuntu-24.04

- pytket/docs/changelog.rst
- pytket/docs/display.rst
- pytket/pytket/circuit/display/__init__.py
- pytket/pytket/circuit/display/static/circuit.html
- pytket/pytket/circuit/display/static/head_imports.html
- pytket/tests/circuit_test.py
- Update circuit renderer link to use v0.10 (includes support for displaying multiple circuits next to each other.)
- Refactor display class to allow saving and loading render options from the pytket config
[Save render options to config](https://github.com/CQCL/pytket-circuit-renderer/issues/44)
> Multi circuit display

- .github/workflows/build_and_test.yml
- CONTRIBUTING.md
- pytket/binders/pauli.cpp
- pytket/binders/zx/diagram.cpp
Update to clang-format 19 as v18 is no longer available on homebrew.
> Use clang-format 19.

- .github/workflows/build-without-conan.yml
- build-without-conan.md
- libs/tkassert/test/conanfile.py
- libs/tklog/test/conanfile.py
- libs/tkrng/test/conanfile.py
- libs/tktokenswap/test/conanfile.py
- libs/tkwsm/test/conanfile.py
- pytket/conanfile.py
- pytket/pytket/_tket/architecture.pyi
- pytket/pytket/_tket/circuit.pyi
- pytket/pytket/_tket/logging.pyi
- pytket/pytket/_tket/mapping.pyi
- pytket/pytket/_tket/partition.pyi
- pytket/pytket/_tket/passes.pyi
- pytket/pytket/_tket/pauli.pyi
- pytket/pytket/_tket/placement.pyi
- pytket/pytket/_tket/predicates.pyi
- pytket/pytket/_tket/tableau.pyi
- pytket/pytket/_tket/tailoring.pyi
- pytket/pytket/_tket/transform.pyi
- pytket/pytket/_tket/unit_id.pyi
- pytket/pytket/_tket/zx.pyi
- pytket/stub_generation/regenerate_stubs
- recipes/pybind11/conanfile.py
- recipes/pybind11_json/all/conanfile.py
- tket/conanfile.py
With the pybind11 update, a new stub function is added in many places in the `.pyi` files generated by pybind11-stubgen. To avoid mypy errors I modified the stub-generation script to add a `# type: ignore` to this function (as I have no idea what the return type should be).
> Update to catch2 3.7.1 and pybind11 2.13.6

- libs/README.md
I don't think we should change the default user and channel, since these labels are meant to inidicate "published" versions. For local library development and testing it's correct to use no labels.
Closes #1529 .
> Add note to libs README about building libraries

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/src/Predicates/PassGenerators.cpp
- tket/test/src/test_CompilerPass.cpp
Allow barriers and wireswaps in `DecomposeSwapsToCXs`.
Fixes #1597 .
> Ensure `CXMappingPass` works on circuits containing barriers or wire swaps

- pytket/docs/changelog.rst
- pytket/docs/conf.py
Identical to 1.33.0rc3 which I've tested locally with the pytket-qiskit and pytket-quantinuum tests.
> Update docs and changelog for 1.33.0 release

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/src/Transformations/PauliOptimisation.cpp
- tket/test/src/test_PauliGraph.cpp
Subcircuit was being constructed assuming that all wires were quantum. Make it use classical wires as well.
Fixes #1578 .
> Fix initialization of subcircuit in `GuidedPauliSimp` implementation

- pytket/pytket/_tket/circuit.pyi
- pytket/pytket/circuit/__init__.py
- pytket/pytket/wasm/__init__.py
- pytket/tests/classical_test.py
The `add_wasm` and `add_wasm_to_reg` functions should now accept `WasmModuleHandler` which is a super class of `WasmFileHandler`.
Follow up to #1503
> fix: update wasm functions to accept `WasmModuleHandler`

- .github/workflows/build-with-nix.yml
- .github/workflows/build_and_test.yml
- .github/workflows/build_libs.yml
- .github/workflows/packages.yml
- .github/workflows/pytket_benchmarking.yml
- .github/workflows/release.yml
- .github/workflows/test_libs.yml
- .github/workflows/test_libs_all.yml
- conan-profiles/macos-13
- conan-profiles/macos-15
- pytket/conanfile.py
- tket/conanfile.py
Closes #1608 .
Use `macos-13` and `macos-15` for the x86 and arm64 builds, respectively.
Release build tested [here](https://github.com/CQCL/tket/actions/runs/11293468007).
> Update macos CI runners

- pytket/conanfile.py
- pytket/docs/changelog.rst
- pytket/tests/predicates_test.py
- tket/conanfile.py
- tket/src/Circuit/CircPool.cpp
A 3 SX gate alternative construction in `_tk1_to_rzsx` is actually expected to be less efficient on hardware than the default case with two Rz gates and one SX gate. This PR removes the alternative construction. See https://github.com/CQCL/tket/issues/1631#issuecomment-2439276370
> Remove hardware inefficient rz-sx decomposition for TK1

- pytket/docs/changelog.rst
- pytket/pytket/circuit/clexpr.py
- pytket/pytket/qasm/qasm.py
- pytket/tests/qasm_test.py
Closes #1644 .
Includes a fix to check the suitability of a pytket circuit for conversion to QASM _after_ calling `DecomposeBoxes()`.
> Add utility method to check register alignment in `ClExprOp`

- pytket/docs/extensions.md
Adding a crosslink to the extensions index to mention pytket-quest. Should I also mention quest explicitly as a density matrix simulator?
Driveby: mention `AerDensityMatrixBackend` from pytket-qiskit which was left out until now.
> docs: link to pytket-quest extensions docs

- pytket/docs/changelog.rst
- pytket/pytket/qasm/qasm.py
- pytket/tests/qasm_test.py
Solves https://github.com/CQCL/tket/issues/1457
> reject incomplete registers in pytket to qasm conv

- pytket/tests/clexpr_test.py
- schemas/circuit_v1.json
> Update JSON schema for `ClExpr` and add validation test

- pytket/binders/circuit/clexpr.cpp
- pytket/docs/circuit.rst
- pytket/docs/circuit_class.rst
- pytket/pytket/_tket/circuit.pyi
Cherrypicking the change from #1658 so we can have the documentation of `ClExpr` in the docs prior to the next release. Is there another commit I need as well?
> docs: cherrypick #1658 onto `docmain`

- pytket/docs/extensions.md
Cherrypick of the change made in #1648 so we can get the updated docs onto `docmain` branch used by the website build.
> cherrypick #1648 onto `docmain` branch

- pytket/setup.py
Otherwise when building locally one may easily miss that the build has failed, which is especially confusing if an old build is already installed.
> Fail CMakeBuild if subprocess fails.

- pytket/binders/passes.cpp
- pytket/conanfile.py
- pytket/docs/changelog.rst
- pytket/pytket/_tket/passes.pyi
- pytket/pytket/passes/auto_rebase.py
- tket/conanfile.py
- tket/src/Predicates/PassGenerators.cpp
`OpType::Collapse` isn't available at the python layer - there is no `OpType.Collapse` - and is not a supported operation in any `Backends` we have. Currently, I don't think it's even possible to construct a pytket `Circuit` with `Collapse` operations, having briefly looked through where it is used.
However, it's proving a blocker on `SequencePass` construction in some places. As an example, `GreedyPauliSimp` supports all the `OpType` required to compile to qiskit & quantinuum hardware, but if added to a `SequencePass` after an `AutoRebasePass`, the `SequencePass` construction fails due to `OpType::Collapse` always being included in the `GateSetPredicate`.
> Remove `OpType::Collapse` from `gen_auto_rebase_pass` `GateSetPredicate`

- pytket/conanfile.py
- tket/conanfile.py
- tket/src/Converters/ZXConverters.cpp
- tket/test/src/ZX/test_ZXSimp.cpp
During extraction, vertices are gradually removed from a ZX graph as we extract gates. Some additional tracking info is maintained via sets and maps of vertices. When vertices are removed, this shouldn't cause issues with looking up remaining vertices in these sets and maps.
HOWEVER, if needed it will perform an input extension which adds new vertices to the graph. Depending on how boost is feeling with memory management, it may reuse the memory locations of removed vertices for these new ones. Because the vertex descriptors are void* pointers under the hood, this clash of memory locations means we can get false positives when looking up vertices in the sets/maps.
#1566 and a related circuit found internally were shown to hit errors during extraction which at first seemed …
> Remove all references to dead vertices in ZX extraction

- pytket/conanfile.py
- tket/conanfile.py
- tket/include/tket/Transformations/CliffordReductionPass.hpp
- tket/src/Transformations/CliffordReductionPass.cpp
Closes #1696 .
Wheels built here: https://github.com/CQCL/tket/actions/runs/12053562141 .
> Only update index map when needed

- pytket/docs/poetry.lock
- pytket/docs/pyproject.toml
Enables sphinx analytics for the docs site.
Configuration file was updated here -> https://github.com/CQCL/pytket-docs-theming/pull/10
> deps: add sphinx analytics dependency

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/include/tket/Transformations/CliffordReductionPass.hpp
- tket/include/tket/Transformations/GreedyPauliOptimisation.hpp
- tket/src/Transformations/GreedyPauliConverters.cpp
- tket/src/Transformations/GreedyPauliOptimisation.cpp
- tket/test/src/test_GreedyPauli.cpp
`GPGraph` construction and `GPGraph::get_sequence` can run significantly longer than the given timeout. This PR updates `greedy_pauli_graph_synthesis_flag` to check timeout during the execution of these methods and to finish early if the timeout is met.
> Timeout on `GPGraph` construction in `GreedyPauliSimp`

- pytket/docs/changelog.rst
- pytket/pytket/utils/outcomearray.py
- pytket/tests/backend_test.py
> Use built-in `int` type for `get_counts()`

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/include/tket/Transformations/SingleQubitSquash.hpp
- tket/src/Transformations/SingleQubitSquash.cpp
- tket/test/src/test_Synthesis.cpp
Fixes #1324 .
Fixes #1357 .
I was a bit concerned about the performance impact of this but it increases the running time of the tket tests by only about 1% so I think it's OK. (If it does turn out to be a problem, an alternative would be never to commute these gates, but that would give poorer results -- or somehow to find a cheaper way to do the check.)
> Add check for graph validity before commuting conditional gates in squashing passes

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/src/Transformations/Rebase.cpp
- tket/test/src/test_Synthesis.cpp
> Rebase to TK2 via TK2 rather than CX

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/include/tket/Transformations/PQPSquash.hpp
- tket/include/tket/Transformations/SingleQubitSquash.hpp
- tket/include/tket/Transformations/StandardSquash.hpp
- tket/src/Transformations/Decomposition.cpp
- tket/src/Transformations/PQPSquash.cpp
- tket/src/Transformations/PhasedXFrontier.cpp
- tket/src/Transformations/SingleQubitSquash.cpp
- tket/src/Transformations/StandardSquash.cpp
- tket/test/src/Passes/test_SynthesiseTket.cpp
- tket/test/src/test_Synthesis.cpp
Initial decomposition into Rx and Rz gates was ignoring conditionals, so these were not being included in the squashing pass.
In general TKET does not do well at detecting and simplifying sequences of conditional gates (with the same condition), and this led to one regression in a unit test for `SynthesiseTket`. Leaving this for future work.
Fixes #1723 .
Fixes https://github.com/CQCL/pytket-quantinuum/issues/557 .
> Squash conditional gates in `SquashRzPhasedX`

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/src/Circuit/macro_circ_info.cpp
- tket/test/src/Circuit/test_Circ.cpp
Fixes #1726 .
This function was implemented using a method where the slice iterator skipped certain vertices, leading to problems when some of those vertices were sources of Boolean wires targeting the unskipped vertices. The new implementation is simpler and avoids this problem.
> Reimplement `Circuit::get_commands_of_type()`

- .github/workflows/release.yml
Tested [here](https://github.com/CQCL/tket/actions/runs/12712092140).
I've set things up on pypi and github so that this works. This seems to be the recommended way.
> Use "trusted publishing" for uploading wheels to pypi

- .github/workflows/build_and_test.yml
- pytket/docs/changelog.rst
- pytket/setup.py
> Add Python 3.13 support to the ZX module

- pytket/conanfile.py
- pytket/docs/changelog.rst
- pytket/tests/predicates_test.py
- tket/conanfile.py
- tket/include/tket/Circuit/Circuit.hpp
- tket/src/Circuit/macro_manipulation.cpp
> Decompose boxes inside conditionals

- pytket/binders/circuit/clexpr.cpp
- pytket/docs/changelog.rst
- pytket/tests/clexpr_test.py
> Fix conversion of `ClOp.BitEq` and `ClOp.BitNeq` to QASM

- pytket/docs/changelog.rst
- pytket/pytket/utils/operators.py
- pytket/tests/utils_test.py
Minor change adding a `get_dict` export for `QubitPauliOperator`. This avoids having to used the undocumented private `_dict` attribute` 
Using `.get_dict` as opposed to `to_dict` here as this new method is not intended for json serialisation.
> feat: add `QubitPauliOperator.get_dict`

- pytket/ruff.toml
- pytket/tests/ansatz_sequence_test.py
- pytket/tests/backend_test.py
- pytket/tests/boxes/phase_poly_box_test.py
- pytket/tests/classical_test.py
- pytket/tests/mapping_test.py
- pytket/tests/mitigation_test.py
- pytket/tests/predicates_test.py
- pytket/tests/pytket_config_test.py
- pytket/tests/qasm_test.py
- pytket/tests/simulator/tket_sim_backend.py
- pytket/tests/tket_sim_test.py
- pytket/tests/transform_test.py
- pytket/tests/utils_test.py
- pytket/tests/zx_diagram_test.py
> Don't ignore unused imports except in init files

- pytket/pytket/utils/term_sequence.py
Pretty sure [this gen_term_sequence_circuit docstring ](https://docs.quantinuum.com/tket/api-docs/utils.html#pytket.utils.gen_term_sequence_circuit) contains a minus sign error as of v.1.39.0. 
I think it should be $e^{-i \frac{\pi}{2} P}$ rather than $e^{i \frac{\pi}{2} P}$.
`PauliExpBox` is used internally by this function which uses the following convention according to the [optype documentation](https://docs.quantinuum.com/tket/api-docs/optype.html)
> docs: fix minus sign in `gen_term_sequence_circuit` docstring

- pytket/conanfile.py
- pytket/docs/changelog.rst
- pytket/pytket/__init__.py
- pytket/pytket/architecture/__init__.py
- pytket/pytket/backends/backend.py
- pytket/pytket/backends/backendinfo.py
- pytket/pytket/backends/resulthandle.py
- pytket/pytket/backends/status.py
- pytket/pytket/circuit/__init__.py
- pytket/pytket/circuit/decompose_classical.py
- pytket/pytket/circuit/logic_exp.py
- pytket/pytket/mapping/__init__.py
- pytket/pytket/placement/__init__.py
- pytket/pytket/utils/distribution.py
- pytket/pytket/utils/results.py
- pytket/tests/simulator/tket_sim_backend.py
- tket/conanfile.py
- tket/src/Circuit/ThreeQubitConversion.cpp
- tket/test/src/test_CompilerPass.cpp
Fixes #1750 .
Drive-by: Apply black formatting to a bunch of python files following black update.
> Make `ThreeQubitSquash` work with circuits containing (some) boxes

- pytket/docs/passes.rst
- pytket/pytket/passes/resizeregpass.py
Fixes #1749 .
From a local build:
> Document `scratch_reg_resize_pass()`

- pytket/binders/circuit/Circuit/main.cpp
- pytket/docs/changelog.rst
- pytket/docs/circuit_class.rst
- pytket/pytket/_tket/circuit.pyi
- pytket/tests/predicates_test.py
- pytket/tests/utils_test.py
* Added a readonly property bound to `Circuit::has_implicit_wireswaps()`
* Added a unit test
* Updated some existing tests -- replaced calls to `Circuit.implicit_qubit_permutation()` if the test only used the result to check for non-trivial permutations
Closes #1665.
> Add `Circuit.has_implicit_wireswaps` property

- pytket/binders/include/circuit_registers.hpp
- pytket/docs/changelog.rst
- pytket/tests/circuit_test.py
> Handle case of unindexed units in `Circuit.q_registers` and `Circuit.c_registers`

- flake.nix
This just lets pytket, within a nix environment, know that its version is 2.0.0.
This is awkward, but versioning is currently managed with setuptools_scm, and nix can't access .git, so the version is hardcoded for the purposes of nix.
None
> Updated the pytket tag to 2.0.0 inside the flake

- pytket/binders/passes.cpp
- pytket/conanfile.py
- pytket/docs/changelog.rst
- pytket/pytket/_tket/passes.pyi
- pytket/tests/predicates_test.py
- tket/conanfile.py
- tket/include/tket/Predicates/PassLibrary.hpp
- tket/src/Predicates/PassLibrary.cpp
- tket/test/src/ZX/test_ZXSimp.cpp
* Added an optional argument to `ZXGraphLikeOptimisation` so that the signature is now
```cpp
const PassPtr &ZXGraphlikeOptimisation(bool allow_swaps = true);
```
The functions in PassLibrary.cpp all use a pattern where we create a local `static const PassPtr` and return it by const reference. In this case, the logic in the `Transform` object used to create the `PassPtr` depends on the value of `allow_swaps`. So I think we need to have two `PassPtr`s, and `allow_swaps` just determines which one we return by reference.
* Added a C++ test, the Python binding, and a Python test.
Closes #1752.
> Zx optimisation swaps

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/src/Predicates/PassGenerators.cpp
- tket/test/src/test_GreedyPauli.cpp
Needed for https://github.com/CQCL/pytket-quantinuum/issues/575 .
Note that `GreedyPauliSimp` [already handles](https://github.com/CQCL/tket/blob/8464c3346d78503fb7e4e5fc8cff28279c7748c4/tket/src/Transformations/GreedyPauliConverters.cpp#L384) `Phase` ops (as a no-op).
> Allow `GreedyPauliSimp` to accept `Phase` gates

- pytket/conanfile.py
- pytket/docs/changelog.rst
- tket/conanfile.py
- tket/src/Transformations/ContextualReduction.cpp
- tket/test/src/test_ContextOpt.cpp
> Fix error in `separate_classical` when quantum ops succeed final measures

- pytket/docs/circuit_class.rst
- pytket/docs/index.rst
Removing this banner as I think its outdated and the issue won't impact any current users. Let me know if you disagree.
Driveby: updated the docs theming submodule -> only impacts the local build of the docs.
Driveby II: add some missing Circuit methods into the docs
> docs: Remove old warning from main page, docs fixes

- pytket/binders/circuit_library.cpp
- pytket/conanfile.py
- pytket/pytket/_tket/circuit_library.pyi
- pytket/pytket/circuit_library/__init__.py
- pytket/tests/circuit_test.py
- tket/conanfile.py
- tket/include/tket/Circuit/CircPool.hpp
- tket/src/Circuit/ControlledGates.cpp
- tket/test/src/test_ControlDecomp.cpp
Implements CnX decompositions from [Maslov (2015)](https://arxiv.org/abs/1508.03273). Related to #1725.
~~Opening this as a draft because there is a problem with the new test that I don't understand, and I wanted to check if it is reproducible in CI. The test passes if I run it with `./test-tket "Scenario: Test CnX_vchain_decomp"`. If I run the whole suite with `./test-tket`, it fails when checking the unitary matrix of the synthesized circuit.~~ I'm still not sure why this is happening; the same check seems to be OK on the Python side.
The paper includes two decompositions (given in Proposition 4 and Proposition 5), both using $\lfloor (n-1)/2 \rfloor$ ancilla qubits to implement a gate with $n$ controls. [Qiskit](https://github.com/Qiskit/qiskit/blob/main/qiskit/synthesis/multi_controlle …
> Decompositions of CnX gates with ancilla qubits

- .github/workflows/build_and_test.yml
- pytket/docs/check_circuit_class_docs.py
- pytket/docs/circuit_class.rst
Checking for missing public methods/properties in the `Circuit` class as there have been significant omissions in the past.
I've tested this by deliberately removing some methods to make sure they are detected. See the change [3a24462](https://github.com/CQCL/tket/pull/1810/commits/3a24462fcd2515e0f1d408251a1f8903e5b75f00) and the corresponding C.I. failure https://github.com/CQCL/tket/actions/runs/13838854885/job/38720844929
There's a sphinx coverage extension that's supposed to detect these sorts of omissions but I haven't managed to configure it properly -> https://www.sphinx-doc.org/en/master/usage/extensions/coverage.html
I don't think the current hacky script will scale well to the rest of the docs. However I still think its worthwhile to check the `Circuit` class in C.I.
> ci: check for `Circuit` class omissions in the docs build

- libs/tktokenswap/conanfile.py
- libs/tktokenswap/test/conanfile.py
- libs/tkwsm/conanfile.py
- libs/tkwsm/test/conanfile.py
I have started a repo ( https://github.com/CQCL/tket-conan-index ) for all the conan recipes from external sources that tket needs or wants to customize. Workflows in that repo build and upload them to the artifactory. (More documentation of this coming soon!) This PR is the first step in moving tket to use these new recipes. Afterwards I'll make a PR for the main library using these versions (and also removing the `recipes` folder and some related workflows from here).
In itself this PR has no effect on tket, which continues to use the existing versions.
> Use tci-boost/1.87.0 in libs, bumping versions.

- pytket/conanfile.py
- tket/conanfile.py
The new version should pull in the latest symengine revision. Without this it seems that conan can't find a suitable version of tket.
> Bump tket version.

- pytket/pytket/circuit/display/static/circuit.html
- pytket/pytket/circuit/display/static/head_imports.html
Circuit renderer by default loads from unpkg.com. If the site is unavailable, introduce a fallback to jsdelivr.net.
There should be minimal chance of both being down at the same time.
Fixes https://github.com/CQCL/tket/issues/1825 .
> add fallback cdn for online circuit renderer

- pytket/docs/changelog.rst
- pytket/pytket/qasm/qasm.py
- pytket/tests/qasm_test.py
Fixes #1833 .
I'd like to make a new release after this.
> Fix handling of `BitWiseOp.NEQ` when parsing QASM

- pytket/conanfile.py
- pytket/docs/changelog.rst
- pytket/tests/predicates_test.py
- tket/conanfile.py
- tket/src/Predicates/PassGenerators.cpp
Fixes #1434 .
I've checked that this doesn't break any tests in pytket-{azure,qir,qiskit,quantinuum} which are the only extensions I can find that use this pass. Unfortunately I can't remember exactly why we [reverted](https://github.com/CQCL/tket/pull/1453) this change previously.
> Keep all classical wires in `FlattenRelabelRegistersPass`

- pytket/docs/changelog.rst
- pytket/pytket/passes/resizeregpass.py
`scratch_reg_resize_pass` defines the transform for a `CustomPass` within its function scope. However, deserialisation is now supported for `CustomPass` but requires the Circuit->Circuit transform as an argument. This PR moves the transform out of the function scope so that custom deserialisation can just import the correct function.
> Add "_gen_scratch_transformation"

- pytket/pytket/backends/backendresult.py
- pytket/pytket/utils/results.py
- pytket/tests/transform_test.py
Just ignoring the errors for now in order to unblock CI.
These errors only appear with numpy 2.2.x. Previously we were constrained to numpy < 2.2 by numba, but numba recently released 0.61.2 which relaxes that constraint.
Closes #1844 .
> Ignore mypy errors

- pytket/binders/circuit/Circuit/add_classical_op.cpp
- pytket/binders/circuit/Circuit/add_op.cpp
- pytket/binders/include/add_gate.hpp
- pytket/docs/changelog.rst
- pytket/pytket/_tket/circuit.pyi
Many of the methods on the pytket `Circuit` class are overloaded to account for the ability for the user to specify arguments as either integers (which implicitly refer to the corresponding index in the standard register for qubits or bits) or explicitly using `Qubit`/`Bit`. This change makes use of variant types (a.k.a. unions) to combine methods whenever possible. This allows us to do things like providing custom error messages for certain kinds of type errors, since we are handling some of the type inference ourselves rather than it all being auto-generated by pybind.
If we like this and wish to push this further, I can imagine further changes off the back of this PR where we take more of the control away from pybind in order to have better control of error messages and API docs by …
> Use variants to merge methods in pybind

- pytket/conanfile.py
- tket/conanfile.py
- tket/include/tket/Circuit/Circuit.hpp
- tket/src/Circuit/setters_and_getters.cpp
- tket/src/Transformations/GreedyPauliOptimisation.cpp
I am suspicious of the move assignment operator, especially of the assignment of the DAG.
While investigating #1858 I found that avoiding its use in `GreedyPauliSimp` stopped one source of leaks. This doesn't prove anything, since the causes of the leaks are quite complicated and it may have just hidden the problem somehow, but when I looked at the move assignment code I couldn't convince myself that all the information was being preserved.
This will mean moves become copies. I don't think this change will have a big effect on performance of `GreedyPauliSimp` as it's only used in one place as far as I can see.
> Undefine move-assignment for `Circuit`

- .github/workflows/release.yml
- pytket/CMakeLists.txt
- pytket/setup.py
Closes #1722 .
We can now build stable ABI wheels for Python >= 3.12. Wheels for Python 3.10 and 3.11 still have to be built separately since nanobind does not support stable ABI wheels below 3.12.
Release workflow tested [here](https://github.com/CQCL/tket/actions/runs/14753995944).
> Build stable-ABI wheels for Python >= 3.12

- pytket/conanfile.py
- tket/conanfile.py
- tket/src/Predicates/Predicates.cpp
Closes #1891 .
Not adding to the hard-coded list of Clifford gates since it doesn't work with tableau methods, but adding as an exception (similar to `Measure`) when checking the predicate.
> Accept Reset in CliffordCircuitPredicate.

- pytket/docs/changelog.md
- pytket/pytket/circuit/clexpr.py
- pytket/pytket/circuit/decompose_classical.py
- pytket/pytket/qasm/qasm.py
This method is used by `pytket-phir`.
I've checked that the pytket-quantinuum tests pass with this change.
> Revert underscoring of has_reg_output.

- pytket/conanfile.py
- tket/conanfile.py
- tket/src/Gate/OpPtrFunctions.cpp
- tket/test/CMakeLists.txt
- tket/test/src/test_Concurrency.cpp
Fixes #1953 .
Along with #1971 this seems to solve the concurrency issue described in the bug report. I have not tested other concurrency scenarios so there may be other issues lurking, but this seems like a good step at least.
We skip the concurrency test for debug builds, as it seems there is still an issue there coming from the teuchos library (used by debug builds of symengine). This warrants further investigation but _may_ be outside our control.
> Try to make tket thread-safe

- pytket/docs/extensions.md
This extension is no longer maintained.
> docs: remove pytket-azure from extensions index

- .github/workflows/release.yml
Towards #2019 .
Tested [here](https://github.com/CQCL/tket/actions/runs/17459658098/job/49581149382).
> Use ubuntu-24.04-arm for Linux arm64 builds.

- README.md
- pytket/docs/index.md
- pytket/package.md
According to slack these "never expire"
closes #2003
> chore: update slack links
